### ISSUE TITLE
Dataset description in search results should use DL body text

### ISSUE THREAD

**Issue by tkeuneman** [TerriaJS/magda#1001]
### Problem description
- Right now the dataset description text is light grey, which may cause problems. Can you please change it to the body default size + colour.

https://designsystem.gov.au/components/body/

### Problem reproduction steps
Go to the search results page

### Screenshot / Design / File reference
<img width="628" alt="screen shot 2018-05-18 at 2 16 37 pm" src="https://user-images.githubusercontent.com/2201814/40215806-1ab75d18-5aa6-11e8-9944-cdf7afe53914.png">

**Comment by adamzerella** [comment]
@tkeuneman Not entirely sure I'm with you here, did you mean like this?

**FROM:**
![image](https://user-images.githubusercontent.com/1501560/40293610-130aa23e-5d15-11e8-8b3f-e20e45dcd455.png)


**TO:**
![image](https://user-images.githubusercontent.com/1501560/40293594-fb44b0fe-5d14-11e8-8b6b-adb9ef935b61.png)

**Comment by tkeuneman** [comment]
Spot on with the colour @adamzerella , please keep the small size
