### ISSUE TITLE
Dataset page: Show full description should be same font size as body

### ISSUE THREAD

**Issue by tkeuneman** [TerriaJS/magda#1003]
### Problem description
The 'Full description' text is too small to be legible. Make it the same font size as the body.

### Problem reproduction steps
Go to the dataset page. It needs to have a long enough description for you to see this.

### Screenshot / Design / File reference
<img width="220" alt="screen shot 2018-05-18 at 2 21 09 pm" src="https://user-images.githubusercontent.com/2201814/40215912-c67bdeb2-5aa6-11e8-86af-d1f1e50923f8.png">

**Comment by adamzerella** [comment]
Duplicated issue -> https://github.com/TerriaJS/magda/pull/992 ?
