### ISSUE TITLE
Dataset page: Open data quality icon 

### ISSUE THREAD

**Issue by tkeuneman** [TerriaJS/magda#1004]
### Problem description
The open data quality icon needs to be aligned with the middle of the stars, which weirdly, it is for the search results page.
Remember to implement this ticket on this page as well: https://github.com/TerriaJS/magda/issues/1000

### Problem reproduction steps
Go to a dataset page

### Screenshot / Design / File reference
<img width="103" alt="screen shot 2018-05-18 at 2 25 34 pm" src="https://user-images.githubusercontent.com/2201814/40216145-25b5723e-5aa8-11e8-8b18-43942f6d3846.png">

**Comment by t83714** [comment]
I think this PR https://github.com/TerriaJS/magda/pull/976
fixed this issue.
It's now in mater and you can have a look again on Dev site.

**Comment by tkeuneman** [comment]
Yup, it's fixed. Shall close
