### ISSUE TITLE
Dataset page: Datasource text

### ISSUE THREAD

**Issue by tkeuneman** [TerriaJS/magda#1008]
### Problem description
This over-writes the DL style guide for no good reason. The font padding is off. Please use the DL body text style for this.

### Problem reproduction steps
Go to a dataset page

### Screenshot / Design / File reference
<img width="582" alt="screen shot 2018-05-18 at 2 39 17 pm" src="https://user-images.githubusercontent.com/2201814/40216343-7169b5fe-5aa9-11e8-9974-f6a8d3020894.png">

**Comment by AlexGilleran** [comment]
This is about bad spacing, it should look like this:

![image](https://user-images.githubusercontent.com/900555/40291187-b2da34dc-5d06-11e8-9a38-f252fbb4e256.png)

Looks like the fault of this:
![image](https://user-images.githubusercontent.com/900555/40291211-d0302cbc-5d06-11e8-95fa-51e335f06a9e.png)
