### ISSUE TITLE
About page: Padding between content and footer is missing

### ISSUE THREAD

**Issue by tkeuneman** [TerriaJS/magda#1009]
### Problem description
Padding between content and footer is missing

### Problem reproduction steps
Go to the about page

### Screenshot / Design / File reference
<img width="966" alt="screen shot 2018-05-18 at 2 42 29 pm" src="https://user-images.githubusercontent.com/2201814/40216413-d311588e-5aa9-11e8-9a6d-fb391a15a3bf.png">

**Comment by AlexGilleran** [comment]
@tkeuneman you can see this at https://magda-dev.terria.io/page/about - please close if it's OK :)

**Comment by tkeuneman** [comment]
Closed!
