### ISSUE TITLE
Feedback form

### ISSUE THREAD

**Issue by tkeuneman** [TerriaJS/magda#1012]
### Problem description
There's a bunch of issues with the feedback form. Let's sit down and go through it together. Headers, link on hover etc.

### Screenshot / Design / File reference
<img width="378" alt="screen shot 2018-05-18 at 4 52 08 pm" src="https://user-images.githubusercontent.com/2201814/40220256-e66ea0e6-5abb-11e8-84af-e130f60f21bd.png">

**Comment by t83714** [comment]
Will review & rebase Chloe's PR (should target 0.39 branch for release) and make sure:
- desktop version feedback button is removed
- mobile version feedback button is removed
