### ISSUE TITLE
Dataset page: Make organisation text go to organisation page

### ISSUE THREAD

**Issue by tkeuneman** [TerriaJS/magda#1016]
### Problem description
Replacing functionality that is now lost. 
When a user is on a dataset page, they can click on the organisation name, which goes to the organisation page.

### Problem reproduction steps
You can see how it's supposed to work on the search results page.
Go to a dataset page to reproduce. Click on the organisation name.

### Screenshot / Design / File reference
<img width="585" alt="screen shot 2018-05-21 at 11 11 07 am" src="https://user-images.githubusercontent.com/2201814/40286136-d7e70936-5ce7-11e8-94b9-380c37f08274.png">

**Comment by adamzerella** [comment]
Not sure how https://github.com/TerriaJS/magda/issues/588 was lost but, it's back now!
