### ISSUE TITLE
Get rid of the heading for filters

### ISSUE THREAD

**Issue by tkeuneman** [TerriaJS/magda#1036]
### Problem description
Removing the heading and padding will make the filters closer to the search bar.

### Screenshot / Design / File reference
![Screen Shot 2018-05-22 at 12.49.23 pm.png](https://images.zenhubusercontent.com/5a5b31cc4b5806bc2bc2a818/9abe91cb-44e1-41b0-9522-d35869714462)

**Comment by chloeleichen** [comment]
do we remove the heading on mobile as well?

**Comment by tkeuneman** [comment]
@chloeleichen No, because it's a drop down
