### ISSUE TITLE
Change tag font to non-opaque

### ISSUE THREAD

**Issue by MelanieHotchkiss** [TerriaJS/magda#1048]
### Problem description
Accessibility.  Use the same colour as the body.  Change the file formats to the same colour.

![image.png](https://images.zenhubusercontent.com/5ac7000f4b5806bc2bcde19f/b563545c-8318-4786-b43d-87e1335987c1)

**Comment by adamzerella** [comment]
@MelanieHotchkiss With the new style: 

<img width="616" alt="screen shot 2018-06-05 at 2 44 10 pm" src="https://user-images.githubusercontent.com/1501560/40955855-1cad98c0-68d0-11e8-87d9-02c1d29d614f.png">


Is accessibility still a problem? Should we make the file formats/text purple?

**Comment by tkeuneman** [comment]
@adamzerella what you've done is perfect. Keep as-is

**Comment by adamzerella** [comment]
@AlexGilleran Ok to close? I believe the issue was resolved when we migrated to purple theme
