### ISSUE TITLE
Change purple footer text to white and underlined

### ISSUE THREAD

**Issue by MelanieHotchkiss** [TerriaJS/magda#1053]
### Problem description

https://files.slack.com/files-pri/T06NVHKFX-FATMBAWPM/screen_shot_2018-05-22_at_3.44.51_pm.png

**Comment by chloeleichen** [comment]
I think this is done

**Comment by MelanieHotchkiss** [comment]
Sorry Chloe - does this one work:  https://files.slack.com/files-pri/T06NVHKFX-FATMBAWPM/screen_shot_2018-05-22_at_3.44.51_pm.png
