### ISSUE TITLE
Changed region type is ignored in search

### ISSUE THREAD

**Issue by AlexGilleran** [TerriaJS/magda#107]
If you do a search (e.g. the suggested Trees in SA2 one on the side) then try to change the region type (e.g. to STE), the search still searches SA2 instead of switching to the new one.

**Comment by chloeleichen** [comment]
this happens when you specify a region in search query, for example: "Trees in SA2:201011002", then when you change region,  the region in search text takes precedence, causing the actual region to not change.

**Comment by AlexGilleran** [comment]
Will be resolved by the filter UI changing.
