### ISSUE TITLE
Make searchApi region / datasets index version configurable

### ISSUE THREAD

**Issue by AlexGilleran** [TerriaJS/magda#1091]
### Problem description
Deploying a new version of the search index, ideally means that we deploy the new indexer with the new version while keeping the search api on the old version, then switch the search api to the new version when the indexer is finished rebuilding the index from the registry.

Back in the days when we used `kubectl` for deployments we used to do this manually, so there's no provision for it in the helm templates. We need to make it so that the search api index versions can be overridden through helm so we can deploy https://github.com/TerriaJS/magda/pull/1088 safely to prod.

**Comment by t83714** [comment]
Good point~
👍
