### ISSUE TITLE
Mobile search placeholder text is too faint

### ISSUE THREAD

**Issue by AlexGilleran** [TerriaJS/magda#1100]
### Problem description
On mobile, on the search results screen, if there's no value in the search box then the text is a very light gray. It should probably be purple to match the search box on the home page.

### Problem reproduction steps
Open in mobile, search for anything, delete the value in the search box.

### Screenshot / Design / File reference
![image](https://user-images.githubusercontent.com/900555/40603434-381f4d42-629f-11e8-9bf3-d4421ce938f7.png)

**Comment by chloeleichen** [comment]
fixed in https://github.com/TerriaJS/magda/pull/1110
