### ISSUE TITLE
Data visualisation: tabs on mobile and desktop

### ISSUE THREAD

**Issue by tkeuneman** [TerriaJS/magda#1111]
### Problem description
- It's hard to see what tab is selected for data visualisation
- Show it using the Design Language component (refer to their website)
- Pay special attention to mobile as when I switch between tabs, it goes to the top of the page.

**Comment by chloeleichen** [comment]
@tkeuneman what about this:
![screen shot 2018-06-05 at 12 46 38 pm](https://user-images.githubusercontent.com/7508939/40952408-8447c634-68be-11e8-8382-9b6af5d4b8f6.png)

**Comment by AlexGilleran** [comment]
Came up in usability testing as #1171 and #1170

**Comment by AlexGilleran** [comment]
@tkeuneman new one, merging the PR for this one 😎

**Comment by tkeuneman** [comment]
Shall I create the ticket?
