### ISSUE TITLE
Mobile: Don't show the map

### ISSUE THREAD

**Issue by tkeuneman** [TerriaJS/magda#1115]
### Problem description
- Hide the national map preview
- Show a secondary button that says 'View in national map' instead

Can you please run this past Tash when done? Ta!

**Comment by chloeleichen** [comment]
What about this:

![screen shot 2018-06-04 at 12 35 31 pm](https://user-images.githubusercontent.com/7508939/40895630-e37e6f34-67f3-11e8-9eea-935582deff56.png)
