### ISSUE TITLE
Show distribution access URLs too, not just download

### ISSUE THREAD

**Issue by kring** [TerriaJS/magda#114]
For example, none of the distributions of this dataset show any links in the UI:
http://magda-dev.terria.io/dataset/c0fd8c78-3b81-4bfe-b586-e6f76ecbce98/details

But there are access URLs:
http://magda-dev.terria.io/api/v0/registry/records/c0fd8c78-3b81-4bfe-b586-e6f76ecbce98?aspect=dcat-dataset-strings&aspect=dataset-distributions&dereference=true

**Comment by chloeleichen** [comment]
Done in https://github.com/TerriaJS/magda/pull/118
