### ISSUE TITLE
Refreshing suggest page at /suggest gives an error

### ISSUE THREAD

**Issue by steve9164** [TerriaJS/magda#1142]
### Problem description
Navigating to /suggest using browser history API is fine, but refreshing the page gives an error:
> Cannot GET /suggest

### Problem reproduction steps
1. Click "Suggest a dataset" in footer
1. Once the suggest form is loaded, click refresh

**Comment by adamzerella** [comment]
@steve9164 I'm not able to replicate this issue locally? Go to `/suggest`, wait for it to load and refresh? I've also tried sending a request then refreshing and it seems fine.

What was the error?

**Comment by steve9164** [comment]
![image](https://user-images.githubusercontent.com/13863530/41017820-0e8805f8-699a-11e8-8da3-f9ab1aea75b3.png)

This is an incompatibility between magda-gateway routes and the /suggest route in React Router, so it will only happen when running the UI through the gateway.

Best fix is probably to move `/suggest` to `/page/suggest`.

**Comment by steve9164** [comment]
Looks like /page/... routes are for static html pages generated from markdown. So instead the fix should be to add the /suggest route into magda-gateway.
