### ISSUE TITLE
About Page - Messy URLs

### ISSUE THREAD

**Issue by sukhrajghuman** [TerriaJS/magda#1143]
### Problem description

Shouldn't have messy links in text. See DTA design guide for including links in text

https://guides.service.gov.au/content-guide/content-structure/#hyperlinks

### Problem reproduction steps
Click the About page link from footer

### Screenshot / Design / File reference

![image](https://user-images.githubusercontent.com/20184809/40955907-88224a38-68d0-11e8-8ec3-81d9c21c73d7.png)

**Comment by adamzerella** [comment]
Those links seem to be 404's anyway :(
