### ISSUE TITLE
Some tag search queries can return results with plain markdown in the preview

### ISSUE THREAD

**Issue by adamzerella** [TerriaJS/magda#1149]
### Problem description
In DatasetSummary when searching using tags. It seems that the markdown isn't parsing correctly on some datasets

### Problem reproduction steps
https://magda-dev.terria.io/search?q=scattering
https://magda-dev.terria.io/search?q=planning

### Screenshot / Design / File reference
<hr>
<img width="738" alt="screen shot 2018-06-05 at 2 47 39 pm" src="https://user-images.githubusercontent.com/1501560/40956385-4ba4d424-68d3-11e8-910c-92b8a2ee3674.png">
<hr> <hr>
<img width="594" alt="screen shot 2018-06-05 at 3 14 07 pm" src="https://user-images.githubusercontent.com/1501560/40956387-4ecd3d4e-68d3-11e8-9400-42e42b1c9fd4.png">

**Comment by AlexGilleran** [comment]
I think this should be solved by still rendering the markdown but being restrictive in the styles that get applied inside it - like having everything the same font, font size etc. Not sure how feasible it is.
