### ISSUE TITLE
On safari browser, Search input box has no placeholder text

### ISSUE THREAD

**Issue by t83714** [TerriaJS/magda#1156]
### Problem description

On safari browser, Search input box has no placeholder text

### Problem reproduction steps

Go to homepage

### Screenshot / Design / File reference
![image](https://user-images.githubusercontent.com/674387/40957191-44ea9566-68d7-11e8-9057-9b511eed8093.png)

**Comment by chloeleichen** [comment]
Fixed https://github.com/TerriaJS/magda/pull/1160

**Comment by t83714** [comment]
@chloeleichen You are the legend! So quick

**Comment by AlexGilleran** [comment]
Still happens for me on Desktop safari, leaving open
