### ISSUE TITLE
Change 'ask a question' button from primary to secondary

### ISSUE THREAD

**Issue by philipgrimmett** [TerriaJS/magda#1161]
### Problem description

"ask a question about this dataset" on the dataset page should be secondary button, but is styled as a primary button. Also should be updated to reflect new colour palette.

### Problem reproduction steps

- Go to any dataset page

### Screenshot / Design / File reference

<img width="483" alt="screenshot 2018-06-05 16 15 33" src="https://user-images.githubusercontent.com/5292858/40958188-b3c1cf3c-68db-11e8-8418-56bb53eadf48.png">

**Comment by chloeleichen** [comment]
Fixed in https://github.com/TerriaJS/magda/pull/1131
