### ISSUE TITLE
Data Preview - Active/Inactive tabs

### ISSUE THREAD

**Issue by sukhrajghuman** [TerriaJS/magda#1170]
### Problem description
If you look at the "data preview" page, it shows both "chart" and "table" tabs are underlined. It makes it hard for the user to know which tab they are on, or even if the other tab is clickable.

### Problem reproduction steps
This is how it currently looks

![image](https://user-images.githubusercontent.com/20184809/41012361-84b6fea2-6984-11e8-9f32-1ba7a873527c.png)

### Screenshot / Design / File reference
This is how it should look

![image](https://user-images.githubusercontent.com/20184809/41012429-d03ef0be-6984-11e8-8269-8c6a2d2acfc3.png)

---
I just changed this to make it look like the above.
![image](https://user-images.githubusercontent.com/20184809/41012332-6ae9e07a-6984-11e8-80c2-4fb8c13c6dce.png)

**Comment by AlexGilleran** [comment]
Duplicate of https://github.com/TerriaJS/magda/issues/1111
