### ISSUE TITLE
Dataset Page: Map not centered

### ISSUE THREAD

**Issue by sukhrajghuman** [TerriaJS/magda#1172]
### Problem description
When I first load a dataset that has a map visualisation, it is not centred around the data.

### Problem reproduction steps
For example, click on [this dataset](https://search.data.gov.au/dataset/ds-dga-ab7eddce-84df-4098-bc8f-500d0d9776d1/details?q=) and scroll down to the map

### Screenshot / Design / File reference
![image](https://user-images.githubusercontent.com/20184809/41012739-6fc73f14-6986-11e8-8fcc-ab5de0384aea.png)

**Comment by AlexGilleran** [comment]
This is actually specific to ASIC datasets... for some reason their WMSes set this up as the coordinates. The coordinates we have the map set to default to are the ones it starts at and the same ones as nationalmap.gov.au - over Australia.

If you open up a non-ASIC WMS like https://search.data.gov.au/dataset/ds-dga-f351b9c7-9a61-41e2-a896-0cd01899b97e/details?q= you'll get a different view.
