### ISSUE TITLE
UX: Show selected/unselected states for data visualisation icons

### ISSUE THREAD

**Issue by tkeuneman** [TerriaJS/magda#1176]
### Problem description
One icon is blue for some reason and the others are grey
- [x] Review icons
- [x] Design selected/unselected states for each

**Comment by philipgrimmett** [comment]
**Design Reference**
![screenshot 2018-06-07 19 41 57](https://user-images.githubusercontent.com/5292858/41091859-eb9b7c68-6a8a-11e8-9f0e-96550ec8f54d.png)

**Icon assets**
[chart-icons.zip](https://github.com/TerriaJS/magda/files/2079865/chart-icons.zip)

**Comment by tkeuneman** [comment]
@philipgrimmett could we have the x and y axis in the two right icons? I suspect that users might need that to ground them in what they'll see if they click on it.

**Comment by philipgrimmett** [comment]
Tried adding axis to the icons but they looked kinda weird. Decided with Tash to leave as it.
