### ISSUE TITLE
Suggest a dataset fixes

### ISSUE THREAD

**Issue by tkeuneman** [TerriaJS/magda#1194]
### QA tasks:

**Suggest a dataset page in footer**
- [x] Make selection colour consistent. It should be the colour that you see in the name selection below
![screen shot 2018-06-07 at 2 49 40 pm](https://user-images.githubusercontent.com/2201814/41078769-12b9d84a-6a62-11e8-9a12-e771813d5c6d.png)
![screen shot 2018-06-07 at 2 49 37 pm](https://user-images.githubusercontent.com/2201814/41078770-12e295dc-6a62-11e8-90bc-745ef745a9e2.png)

**Suggest a dataset in search results**
- [x] Make the text in the middle of the borders
- [x] Make it H3
- [x] Make the chevron bigger and centred with the text
![searching_for___data_gov_au](https://user-images.githubusercontent.com/2201814/41079311-ab12c7da-6a64-11e8-9c17-fc41847982a6.png)
- [x] Remove * from form as all things are compulsory. 
- [x] Introduce a secondary button that says 'Cancel' and clears the form
![searching_for___data_gov_au_2](https://user-images.githubusercontent.com/2201814/41079357-dd17a0d4-6a64-11e8-8c8d-358f4afe49ea.png)

**Ask a question about this dataset**
- [x] Make this a secondary button
- [x] Change the text to ask *a* question about this dataset
![banners_and_alerts_and_2016_soe_biodiversity_nrs_protection_level_of_ibra_regions_in_2011_data_gov_au](https://user-images.githubusercontent.com/2201814/41079393-05da8f54-6a65-11e8-9796-3fcf58ec587a.png)
 
- [x] Make the box 800px wide, and right-aligned
- [x] Remove asterix
- [x] Add cancel button that clears form
- [x] Review random thin line
- [x] @philipgrimmett to add updates 'x' as it looks really thin in the new style. 
- [x] Blur the background when the modal is up: https://css-tricks.com/receding-background-modal-boxes/ I normally put these in my mock ups, my bad for letting this one pass.

![2016_soe_biodiversity_nrs_protection_level_of_ibra_regions_in_2011_data_gov_au](https://user-images.githubusercontent.com/2201814/41079690-2e215c76-6a66-11e8-935e-ca9cf79d4fd3.png)

**Comment by sukhrajghuman** [comment]
@tkeuneman 
the colors around the border are a bit annoying. I'm just using the design system components as they are and haven't changed css colors for any of these. I think it's an issue to do with colour migration @chloeleichen ?

I'm not getting the random thin line either. I've tried on different browsers and screen sizes hmmm...

**Comment by sukhrajghuman** [comment]
okay i just started getting the random thin line too now, its all fixed now.

**Comment by sukhrajghuman** [comment]
okay fixed the color thing too
