### ISSUE TITLE
Add "Go to Source" link in accordion view

### ISSUE THREAD

**Issue by ajbar7** [TerriaJS/magda#147]
In non-accordion view would it be possible to put a "Go to Source" view that links to the same link as source link on data set page? Like 

![image](https://user-images.githubusercontent.com/7380633/28255093-6e73f498-6af6-11e7-8eaa-7a8e8e8a0579.png)

**Comment by chloeleichen** [comment]
Where does the button go, the landing page?

**Comment by ajbar7** [comment]
@chloeleichen it would go to the source portal link so for example for the one above it would go to http://www.bom.gov.au/metadata/19115/ANZCW0503900210 as per http://search.data.gov.au/dataset/ANZCW0503900210/details
