### ISSUE TITLE
consider change from "by" for publisher syntax

### ISSUE THREAD

**Issue by bsimyo** [TerriaJS/magda#15]
I think we should reconsider the use of "by" in the query language for limiting the search to a particular publisher.  That is because:
a) "by" isn't an exact fit for the relationship between a dataset and a publisher (the publisher is making the data available - they may not have created it - it may have been created by a different agency).  "From" is closer to the meaning we want (there may also be other possibilities); and
b) I think we'll later need to use "by" for influencing display of results (eg for sorting and/or grouping - eg "population by state") and it would be good if people didn't get in the habit of using it.

I think that overloading "from" to allow a trailing publisher or date is fine and easy to disambiguate.  I think that it won't be possible to do so between "by" and the likely future use of "by" I mentioned above.

So, I think we should use "from" for publisher instead of "by".  What do others think?

**Comment by AlexGilleran** [comment]
No search syntax any more = no problem.
