### ISSUE TITLE
Map preview should zoom to dataset

### ISSUE THREAD

**Issue by kring** [TerriaJS/magda#159]
This will probably require a change to TerriaJS.  We have a `zoomOnEnable` property, but it's ignored on initial load for questionable reasons.

**Comment by kring** [comment]
The TerriaJS support is available with TerriaJS/terriajs#2637, just need to use this flag in Magda.

**Comment by tristochief** [comment]
hey kevin where abouts is everyone today?

**Comment by kring** [comment]
The above fix didn't work, because it turns out `generatePreviewData.js` isn't actually used!

The correct place to add `zoomOnEnable` is `previewDataActions.js`.  @tristochief  can you also please remove `generatePreviewData.js` since it isn't used anymore?

**Comment by tkeuneman** [comment]
@t83714 could you estimate on this?

**Comment by t83714** [comment]
Hi @tkeuneman
Just added a new commit a few minutes ago. 
The PR is now passed CI build and ready for QA & Merge now.
See [here](https://github.com/TerriaJS/magda/pull/458)
