### ISSUE TITLE
CSW Connector adds incomplete source URL

### ISSUE THREAD

**Issue by kring** [TerriaJS/magda#177]
For example, http://search.data.gov.au/api/v0/registry/records/3dde8eac-03e7-4572-8661-67424bb510fe?aspect=dataset-distributions&dereference=1&aspect=source has:
```
"source": {
  "url": "https://data.thelist.tas.gov.au:443/datagn/srv/eng/csw",
  "name": "Tasmania TheList",
  "type": "csw-dataset"
}
```

The `url` should be something like: https://data.thelist.tas.gov.au/datagn/srv/eng/csw?service=CSW&request=GetRecordById&version=2.0.2&id=3dde8eac-03e7-4572-8661-67424bb510fe&outputSchema=http://www.isotc211.org/2005/gmd

**Comment by kring** [comment]
Ideally it should be a human-friendly landing URL rather than that XML document, if one is available.

**Comment by steve9164** [comment]
The source code for the web client that renders the source link can be found [here](https://sourcegraph.com/github.com/TerriaJS/magda/-/blob/magda-web-client/src/Dataset/DatasetDetails.js#L16:104) and that URL seems to come from the CSW connector [here](https://sourcegraph.com/github.com/TerriaJS/magda/-/blob/magda-csw-connector/aspect-templates/dcat-dataset-strings.js?q=landingPage&o=case#L41:16)

**Comment by AlexGilleran** [comment]
Judging by https://search.data.gov.au/api/v0/registry/records/ds-listtas-3dde8eac-03e7-4572-8661-67424bb510fe?aspect=source this is better now.
