### ISSUE TITLE
Replace GA FIND harvester with Harvest Nodes

### ISSUE THREAD

**Issue by tobybellwood** [TerriaJS/magda#18]
Here are the CSW endpoints to replace the GA-FIND harvester with - not a current priority, but a next step.

We should also update the ignoreHarvestSources for data.gov.au as follows:

ignoreHarvestSources = [
"FIND (http://find.ga.gov.au) CSW Harvester",
"Brisbane City Council CKAN Harvester",
"Data NSW CKAN Harvester",
"Data SA CKAN Harvester"
"Australian Institute of Marine Science CSW Harvester"
"Navy Meteorology and Oceanography (METOC) CSW Harvester"
"Mineral Resources Tasmania CSW Harvester"
"Tasmania Department of Primary Industries, Parks, Water and Environment CSW Harvester"
]

And here are the replacement CSW's.  There will be a fuller list of CSWs coming from GA at some point.
There is also a harvest node (QLD spatial) that isn't CSW - we'll need to work that out when we build new connectors

<s>### Atlas of Living Australia
http://spatial.ala.org.au/geonetwork/srv/eng/csw?SERVICE=CSW&VERSION=2.0.2&REQUEST=GetCapabilities</s>

### Australian Bureau of Meteorology
http://www.bom.gov.au/geonetwork/srv/eng/csw?SERVICE=CSW&VERSION=2.0.2&REQUEST=GetCapabilities

### Australian Institute of Marine Science 
http://data.aims.gov.au/geonetwork/srv/eng/csw?SERVICE=CSW&VERSION=2.0.2&REQUEST=GetCapabilities

### Australian Oceans Data Network
http://catalogue.aodn.org.au/geonetwork/srv/eng/csw?SERVICE=CSW&VERSION=2.0.2&REQUEST=GetCapabilities

### Geoscience Australia
http://www.ga.gov.au/geonetwork/srv/en/csw?SERVICE=CSW&VERSION=2.0.2&REQUEST=GetCapabilities

### CSIRO Marlin
http://www.marlin.csiro.au/geonetwork/srv/eng/csw?SERVICE=CSW&VERSION=2.0.2&REQUEST=GetCapabilities

### Terrestrial Ecosystem Research Network 
http://data.auscover.org.au/geonetwork/srv/eng/csw?SERVICE=CSW&VERSION=2.0.2&REQUEST=GetCapabilities
-or-
http://geonetwork.tern.org.au/geonetwork/srv/eng/csw?SERVICE=CSW&VERSION=2.0.2&REQUEST=GetCapabilities

### Mineral Resources Tasmania 
http://www.mrt.tas.gov.au/web-catalogue/srv/eng/csw?SERVICE=CSW&VERSION=2.0.2&REQUEST=GetCapabilities

### Tasmania TheList
https://data.thelist.tas.gov.au:443/datagn/srv/eng/csw?SERVICE=CSW&VERSION=2.0.2&REQUEST=GetCapabilities

### NSW Land and Property 
https://sdi.nsw.gov.au/csw?Request=getCapabilities&Version=2.0.2&Service=CSW

**Comment by tobybellwood** [comment]
This looks like it might be moving up the priority list.  Is it worth experimenting with the replacement list of CSW endpoints now?

**Comment by AlexGilleran** [comment]
I put all of those in and they seem to be requesting data OK, but not sure what to do about where to link to for some of them - FIND had a web landing page for every dataset but some of these don't seem to have any equivalent.

**Comment by tobybellwood** [comment]
GA's CSW is the first priority - and we'll then stage the other ones.

**Comment by tobybellwood** [comment]
Removed ALA from the list - there are better ways of interacting with their catalog.

**Comment by tobybellwood** [comment]
Add new CSW harvester:

### National Environmental Information Infrastructure

http://neii.bom.gov.au/services/catalogue/csw?
SERVICE=CSW&VERSION=2.0.2&REQUEST=GetCapabilities

**Comment by AlexGilleran** [comment]
NEII is added - they seem to all be National Environmental Information Infrastructure anyway so I don't think we desperately need the override?
