### ISSUE TITLE
Use MAGDA to manage the NationalMap catalog

### ISSUE THREAD

**Issue by kring** [TerriaJS/magda#182]
This would allow:
* Much faster and better searching of the catalog.
* Easy exclusion of datasets that aren't going to work (e.g. based on aspects: broken link, format)
* Smaller initial catalog download.
* (Eventually) interactive catalog editing.

Some things we will need:
* [ ] A representation of a group of items in the registry, probably as a record. Or can we use Projects?
* [ ] Scoped searches, i.e. "find all datasets matching this criteria that are in this group or any groups it contains". This isn't necessary if we assume that NationalMap has its own Magda instance, which might be fine in the short term.
* [ ] MagdaCatalogGroup in TerriaJS.
* [ ] Integration of the TerriaJS search with the MAGDA search API.
* [ ] Connector to populate groups/datasets/distributions from a TerriaJS catalog JSON file. Helpful to seed a Magda registry from an existing TerriaJS catalog, but maybe not that useful in general.
* [ ] UI for editing groups and datasets
* Probably lots more...

Do groups contains datasets, distributions, or both?

If a group can contains datasets, how do we decide which distribution in a dataset to use in TerriaJS?  TerriaJS's `CkanCatalogItem` has some logic for this, but it's not great.

**Comment by tkeuneman** [comment]
@kring are you comfortable with us closing this ticket? Unlikely to fit it into one sprint.

**Comment by kring** [comment]
Sure, that's why it was marked epic. ;)
But yeah, it's ok to close it.  It probably properly belongs in a different project, really.
