### ISSUE TITLE
Create data.json connector

### ISSUE THREAD

**Issue by tobybellwood** [TerriaJS/magda#19]
The data.json format (https://github.com/GSA/ckanext-datajson) is used extensively around open data portals - most specifically (in Australia) to connect to Socrata and ArcGIS online portals, but also extensively in the USA.  Currently we harvest into data.gov.au (although this is not reliable).

For example:
Socrata:
http://www.data.act.gov.au/data.json
https://data.melbourne.vic.gov.au/data.json
https://data.sunshinecoast.qld.gov.au/data.json
ArcGIS Online:
http://data-1.hobartcc.opendata.arcgis.com/data.json
http://opendata.launceston.tas.gov.au/data.json
http://data.logancity.opendata.arcgis.com/data.json
http://data.moretonbay.qld.gov.au/data.json
http://data.goldcoast.opendata.arcgis.com/data.json
http://vicroadsopendata.vicroadsmaps.opendata.arcgis.com/data.json

**Comment by kring** [comment]
Done, see https://github.com/TerriaJS/magda/tree/master/magda-project-open-data-connector.
