### ISSUE TITLE
Are we able to filter out sources via a URL to the search API?

### ISSUE THREAD

**Issue by tobybellwood** [TerriaJS/magda#20]
Thinking down the track - we currently operate a "Search Results Sharing Partnership" - currently with SA and NSW.  This is achieved by the CKAN portals running a modified ckanext-harvest (https://github.com/datagovau/ckanext-harvest) plugin to remove the redirect loop it creates.

What if we were able to facilitate a CKAN plugin that did the same role, but excluded the requestor's portal, thus giving users of the plugin access to the full (new) data.gov.au results?

**Comment by AlexGilleran** [comment]
Don't think this is really in scope for us anymore.
