### ISSUE TITLE
Make sleuther framework use "hey I'm back" functionality

### ISSUE THREAD

**Issue by AlexGilleran** [TerriaJS/magda#220]
Right now it takes a new event to keep the queue going - this means if something goes wrong no crawl happens for a week, the search indexers / sleuthered aspects will be stale for that long.

Also right now webhook consumers do a full crawl on startup in case they missed anything, which takes a lot of CPU time.

Flow should be more like:

- Wake up
- Check if webhook exists
  -> Exists? Send "hey I'm back"
  -> Doesn't exist? Register it and crawl all the things.

This will need to be done for the sleuther framework and for the indexer.

**Comment by kring** [comment]
There actually is a "hey I'm back" service.

```
POST /api/v0/registry/hooks/whatever-id/ack

{
  "succeeded": false
}
```

Any pending webhook events will be raised immediately after this service.  This will also get things moving again if the indexer/sleuther/whatever crashed while processing a webhook event that had been deferred.  More details here https://github.com/TerriaJS/magda/pull/178.

**Comment by AlexGilleran** [comment]
Oh rad - issue modified.
