### ISSUE TITLE
Sitemap has dead links

### ISSUE THREAD

**Issue by soyarsauce** [TerriaJS/magda#262]
Re: dead links, there seem to be some dead links in the sitemap itself. We should aim to keep the sitemap free of dead links, the generation process needs to be tweaked to catch any dead links.
e.g.
From:
http://magda-dev.terria.io/sitemap/dataset/afterToken/0
Links to:
http://magda-dev.terria.io/dataset/https%3A%2F%2Fwww.data.act.gov.au%2Fapi%2Fviews%2Fmxrr-vuy8
(in fact majority of the links on this sitemap are 404s)
Server headers also respond with a 200, seperate issue: https://github.com/TerriaJS/magda/issues/263

![image](https://user-images.githubusercontent.com/9134432/33539772-141d88da-d91c-11e7-8821-999704006c4e.png)

**Comment by AlexGilleran** [comment]
This was always a problem with the ACT ones, presumably because of encoding. Appears to be fixed by @steve9164's encoding fixes.
