### ISSUE TITLE
Update headings to be more accessible & SEO friendly

### ISSUE THREAD

**Issue by soyarsauce** [TerriaJS/magda#265]
Tweak the heading structure to be more accessible & SEO friendly.

I'd recommend making "Australian open data search" a h1 only for the homepage, and a not-heading-element for any other pages. This will fix the unnecessary double h1 across the majority of the routes where there is already an existing h1 where it makes sense.

**paginated results routes:**
http://magda-dev.terria.io/publishers
http://magda-dev.terria.io/projects
Search result headings - h3s > h2s

**project route:**
http://magda-dev.terria.io/projects/4745be90-d0c4-11e7-aec4-9bd95a1f7bd9
`Description`, `Discussion` h3s > h2s

**search page:**
http://magda-dev.terria.io/search?q=rain
Add h2s to the results

**dataset route:**
http://magda-dev.terria.io/dataset/ANZCW0503900371/details
`Overview`, `Source`, `Data and APIs`, `Temporal coverage` should be h2s
Links under Data and APIs can then remain as h3s with this change 

Move `show preview` button out of the h3 element

`Tags` as a h5 - either remove the heading element (retain styles via css) or update to.. a h3, but still doesn't fit the structure of the page.. This one is a tough call.

There are probably some other routes but I'm unable to browse the dev site at the moment with the intermittent API responses.

**Comment by tkeuneman** [comment]
@philipgrimmett we should look into this
