### ISSUE TITLE
Add an API for projects

### ISSUE THREAD

**Issue by kring** [TerriaJS/magda#272]
We need to add a `magda-project-api` component in order to solve two problems:
1. No one creates the `project` aspect, so we currently have to create it manually.
2. Currently logged-in users can create registry entries with any not-previously-used ID.  The UI always uses a GUID, but the API does not enforce this. This is bad because an ID chosen by a malicious user could collide with a future ID.

So the project API would create the required aspect on startup, and it would provide an API for creating and accessing projects that enforces a namespace ID (e.g. prefix project IDs with `prj-`).

**Comment by kring** [comment]
With this abstraction, projects do not necessarily even need to be stored in the registry.

**Comment by tkeuneman** [comment]
Out of scope atm.
