### ISSUE TITLE
Add ability to exclude publisher from results

### ISSUE THREAD

**Issue by tobybellwood** [TerriaJS/magda#28]
In this scenario - the dominant publisher adds no value to the results, and should be excluded:
![image](https://cloud.githubusercontent.com/assets/4373945/23787352/c1004cac-05c5-11e7-8ac2-3227acdb9985.png)
Asuming this is easy in ES, a UI tweak to +/- the line and maybe a rework of the x to remove may be needed?

**Comment by AlexGilleran** [comment]
I'm not sure about this one - won't it be confusing that the most common publisher isn't there?

**Comment by kring** [comment]
I think Toby is just talking about a filter that lets you exclude a publisher.  Not that it would also exclude the most common one or anything like that.

**Comment by AlexGilleran** [comment]
Ah right

**Comment by tkeuneman** [comment]
Will be rolled into part of the search re-design.
