### ISSUE TITLE
Search - review current features 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/magda#287]
Review current features, including results from Optimizer to prep for mockup designs.

**Comment by tkeuneman** [comment]
https://docs.google.com/spreadsheets/d/1_RCPuErx9eCqJRo2twNvaMeE1S2SHU3uMeKhscofcKo/edit?usp=sharing

Heatmap:
[Search results heatmap 01-03-18.zip](https://github.com/TerriaJS/magda/files/1617539/Search.results.heatmap.01-03-18.zip)
