### ISSUE TITLE
Search - new UI for results page

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/magda#290]
- [x] Comparative analysis (available [here](https://docs.google.com/spreadsheets/d/1gonsM15zApTUISZvoRtko8xlEysm6ErKSqxqJAbVU-M/edit?usp=sharing))
- [x] Analysis of what to include, what not to include
- [x] Wireframe
- [ ] Set metrics of success
- [ ] First iteration of design, including mobile for search filters and search results

**Comment by tkeuneman** [comment]
@philipgrimmett would you be able to review the changes I have made and make amendments etc before this sprint ends?
