### ISSUE TITLE
Design: Search - data quality calculation visible

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/magda#291]
- [x] Write up data quality page and tooltip content
- [x] Get feedback
- [x] Design page V1
- [x] Design page V2

**Comment by tkeuneman** [comment]
Please have a look at the data quality calculation text and give feedback! Layout could do with some work and I need some help with a closing paragraph. https://invis.io/KBFHHJUZJUA#/275176493_DATA_QUALITY_01_01_01_TK-2x
