### ISSUE TITLE
Search - error message and "no results" page

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/magda#292]
- [x] The ability to see useful datasets and request a dataset when there are 0 search results
- [x] The ability to be told that if you removed one filter, you'll get x more results
- [x] The ability to request a dataset if the dataset isn't available
- [x] The ability to see private datasets (in the sense that they exist but you can't access them unless you have authorisation)
- [x] Request/report/communicate dataset forms has smarts that reduce spam
- [x] Spreadsheet with logic

**Comment by tkeuneman** [comment]
https://confluence.csiro.au/x/3oJEIg

**Comment by tkeuneman** [comment]
@maxious Would you be able to add to this ticket what you need for the smarts that will reduce spam?

**Comment by maxious** [comment]
The simplest trick is the "honeypot" - put a CSS obscured field that should not be filled in and responses are rejected if anything is in that field. Basic spam bots just spam everything.

For more advanced analysis, https://akismet.com/development/ is a paid API that can scan the contents of a comment

**Comment by tkeuneman** [comment]
Thanks @maxious

**Comment by tkeuneman** [comment]
Copy from Martia:
Copy for data set request automatic email response.

[This one is for direct requests to an organisation (either a broken url, or something missing, or a question etc)]
Your request has been forwarded to the data owner. A representative of this agency/organisation will contact you shortly.
Please note that the time taken to action your request may vary, depending on the nature of the request and the agencies publishing processes.

[And a more general auto response for data set requests where a data owner may be unknown or optional:]
Your request has been sent.
The relevant agency/organisation for the data you require, or a representative of the Digital Transformation Agency, will contact you shortly.
Please note that the time taken to action your request may vary depending on the nature of the request.

**Comment by tkeuneman** [comment]
**For the general auto-response can we say:**
"Your request has been sent!

Someone from the Australian Digital Transformation Agency or the organisation that handles the relevant data will get in touch soon. 

Please note that the time taken to action your request may vary depending on the nature of the request."

**For an organisation question or report an issue:**
"Your request has been sent to the data owner! 

Someone from this organisation will get in touch soon.

Please note that the time taken to action your request may vary, depending on the nature of the request and the publishing process."

**Comment by tkeuneman** [comment]
Changing text from 'Request a dataset' to 'Suggest a dataset' to have softer wording.
