### ISSUE TITLE
Homepage - review current + comparative analysis

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/magda#293]
- [x] Review current page

- [x] Set up and analyse heatmaps 

- [x] Comparative analysis

**Comment by tkeuneman** [comment]
Comparative analysis: https://confluence.csiro.au/display/MAGDA/Homepage%3A+Comparative+Analysis
https://docs.google.com/spreadsheets/d/1gonsM15zApTUISZvoRtko8xlEysm6ErKSqxqJAbVU-M/edit?usp=sharing

**Comment by tkeuneman** [comment]
![datagovau heatmap](https://user-images.githubusercontent.com/2201814/36570017-43c53838-1884-11e8-8006-93df38bc3a5d.png) Heatmap of 2,600 clicks. 

Things to note: 
- 47% clicks are on the search bar
- 10% are on 'datasets' in the header
- Request datasets gets 1% of clicks
- The first popular tag gets 1% of clicks and the others are negligible
- Dataset counts get 2% of clicks
- Search.DGA has 5% of clicks 
- The open data toolkit has 1% of clicks despite being the last link in a long slab of text. 
- National map has 1%
- Login/Register has less than 1% of clicks
