### ISSUE TITLE
Home page - mockup designs: web and mobile

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/magda#294]
For the australian public, Who need access to high-quality and usable government data, Data.gov.au is a robust and user friendly system That is able to expose data and metadata produced by federal, state and local governments, in both human-readable and machine-friendly formats.

Delight all users
Show use cases
Featured APIs
Featured datasets
Toolkit
Social media (based on factors)

**Comment by tkeuneman** [comment]
Variations are up here: https://www.figma.com/proto/F9ts1TVYBqkO14z2YPh5dSJq/Homepage_MAGDA_V3_06032018_TK?node-id=68%3A0&scaling=contain

**Comment by tkeuneman** [comment]
Final designs: https://www.figma.com/file/F9ts1TVYBqkO14z2YPh5dSJq/Homepage_MAGDA_V4_12032018_TK?node-id=104%3A11

Interaction:
https://drive.google.com/open?id=1NwlGpcZRYEJUFk2Un58whoCPvweezoen
