### ISSUE TITLE
Research and text: Use cases

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/magda#296]
- [x] identify use cases using user research to date

- [ ] contact min 10 case owners

- [ ] interview and prepare the use cases drafts, images, disclaimers etc

**Comment by AnaBelgun** [comment]
To start working on identification of use cases in Sprint 1.

**Comment by AnaBelgun** [comment]
DTA suggested we use the current https://data.gov.au/showcase list of cases when building the home page. 
They will start reviewing that list to update it.

**Comment by tkeuneman** [comment]
@AnaBelgun I'll move this issue out of the sprint in the interim.
