### ISSUE TITLE
As a data professional, I want to see at a glance what area on a map is affected by the dataset I'm looking at

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/magda#303]
- [ ] I can move in and out of the map
- [ ] I can see what area has related data

**Comment by AlexGilleran** [comment]
Needs a bit more detail or maybe designs - is this related to the TerriaJS previewer or is this something else?

**Comment by tkeuneman** [comment]
@t83714 would you say this ticket is done? Looks like it.

**Comment by t83714** [comment]
@tkeuneman I think the auto-zoom feature (issue #159 & PR https://github.com/TerriaJS/magda/pull/458) should have addressed this issue.
