### ISSUE TITLE
The ability to search without keywords pre-defining a filter

### ISSUE THREAD

**Issue by tkeuneman** [TerriaJS/magda#334]
Right now what a user inputs into the keyword search could add a filter that affects the search results. This ticket is about omitting this functionality.

- Matches relevance of keywords, by priority, for file format and organisation, to see what appears.

**Comment by AlexGilleran** [comment]
Are you sure this is supposed to be in QA @chloeleichen ? I haven't changed it on the server and it appears to still happen?
