### ISSUE TITLE
Investigate use of Google Cloud Functions and other options for connectors and indexers

### ISSUE THREAD

**Issue by kring** [TerriaJS/magda#34]

**Comment by AlexGilleran** [comment]
Not a lot of good news on this front.

https://github.com/fission/fission looks promising (runs on k8s so no lock-in) but it's in alpha.

https://funktion.fabric8.io/ is a similar concept but seems very tied in with using fabric8.

https://serverless.com/framework/docs/ is the main player in the space - it's not totally open with where you can run it but at least you have the choice of AWS, OpenWhisk or Azure. The thing is there's still quite a bit of lock-in there, and they're a funded corp that's developing their own platform - is the openness gonna become a second class citizen?

**Comment by kring** [comment]
We're using jobs for this now; seems to work pretty well.
