### ISSUE TITLE
When I'm signed in, I have no way to sign out

### ISSUE THREAD

**Issue by tkeuneman** [TerriaJS/magda#342]
<img width="1224" alt="screen shot 2018-01-12 at 9 56 35 am" src="https://user-images.githubusercontent.com/2201814/34851639-130a196e-f77f-11e7-87ae-a8de4c2a42e9.png">

**Comment by AlexGilleran** [comment]
Normally "Sign In" changes to "Sign Out", looks like the sign in failed somehow :(

**Comment by AlexGilleran** [comment]
Same root cause as #341
