### ISSUE TITLE
As a data journalist, I want to filter by location

### ISSUE THREAD

**Issue by tkeuneman** [TerriaJS/magda#357]
- [x] As a developer, I want to see what location options are available to me: map and search
- [ ]  If I click on the location search bar and I haven't typed anything, I see a prompter that lets me know what locations I can search for. [Designs](https://user-images.githubusercontent.com/2201814/34861178-13ef2b70-f7b7-11e7-8096-29ac0a2680d3.png)
- [x] As a curious end user, I want to filter by location using the map so I can see what data sets are relevant to my suburb, in this case, Belconnen. User has to search for Belconnen (LGA or by post code) or user can not search by map, map shows the selected area after search is applied. [Designs](https://invis.io/HVF8ORL7P#/272862064_searchResults_01_03_01)
- [x] As a government researcher, I want to see the employment statistics for SA2:201011002
- [x] Unless the user has specifically entered SA1, SA2, SA3, SA4, or one of the SA numbers, e.g: 201011002, do not show SAs in the search results. This changes the rules from SA1 areas inheriting the names from SA2s
- [x] As a data journalist, I want to quickly search for ATO details for Victoria. [Designs](https://invis.io/HVF8ORL7P#/272862064_searchResults_01_03_01)
- [x] As an end user, I want to be able to search by state acronyms, e.g. NSW, QLD. Add the acronyms for states and territories into search by location
- [x] As a end user, I have the ability to search by keyword input or by clicking on a state

![searchresults_01_03_02](https://user-images.githubusercontent.com/2201814/34859514-c2917fc8-f7aa-11e7-8daa-5b1b35479e32.png)
![searchresults_01_03_03](https://user-images.githubusercontent.com/2201814/34859515-c2c012fc-f7aa-11e7-98aa-11a0221d93e1.png)
![searchresults_01_03_04](https://user-images.githubusercontent.com/2201814/34859516-c2ed2436-f7aa-11e7-80d3-996ea470620c.png)

**Comment by chloeleichen** [comment]
@AlexGilleran currently this request: http://magda-dev.terria.io/api/v0/search/regions?query=SA2:201011002 yields no result
