### ISSUE TITLE
UI: Implement home / landing page

### ISSUE THREAD

**Issue by kring** [TerriaJS/magda#37]

**Comment by AnaBelgun** [comment]
Adding the tasks discussed on 31 May 17:

- [ ] select example search queries for "Try searching for..." box - @cam-grant 

- [ ] Repository statistics to include: - @AlexGilleran @chloeleichen 
- total number of datasets
- total number of harvested sources
- total number of spatial datasets
- if time, ES query for total number of openly licensed datasets

- [ ] Featured datasets - manual curation through weekly updates (TBC) @cam-grant @ajbar7

- [ ] Featured datasets - use static JSON file with list of featured dataset record IDs @chloeleichen 

- [ ] Use data.gov.au RSS feed (https://blog.data.gov.au/blogs/rss.xml)

**Comment by kring** [comment]
Closing this, we have separate issues for the remaining items.
