### ISSUE TITLE
Connectors Now Require ID but this isn't being passed in

### ISSUE THREAD

**Issue by AlexGilleran** [TerriaJS/magda#379]
The connector code now requires an `--id` but our generated connector config doesn't pass it. We need to modify the connector generation to include this.

**Comment by kring** [comment]
I think the connector configs all already have an `id`, e.g. https://github.com/TerriaJS/magda/blob/master/deploy/connector-config/act-government.json#L3.

But if you have an old connector configmap on your cluster, it won't have the new id property.

**Comment by AlexGilleran** [comment]
Yeah but they're not getting `--id 12345` when they start up, at least not on dev.

Or am I missing a step?

**Comment by kring** [comment]
Through the magic of yargs, any keys in the file referenced with `--config` become parameters.  So as long as the configmap has an `id` key, the `id` parameter will be passed on the command line.

**Comment by AlexGilleran** [comment]
OK so with a config map update on dev we're all good :)
