### ISSUE TITLE
Selected filter not returned in result with hitCount

### ISSUE THREAD

**Issue by chloeleichen** [TerriaJS/magda#386]
in this query: http://magda-dev.terria.io/api/v0/search/datasets?query=water+by+Adelaide%20City%20Council++by+Courts%20Administration%20Authority&start=0&limit=10

I have `Adelaide City Council` selected through the UI but it's not returned in the `facet` field of the results

**Comment by AlexGilleran** [comment]
Looks like it's only a problem if you have 2 spaces (e.g. the `++by`).

In any case this is obsoleted by #334
