### ISSUE TITLE
Release latest UI

### ISSUE THREAD

**Issue by chloeleichen** [TerriaJS/magda#391]
Minor stuff that might not even be wanted at this stage:
- [x] * No spaces between tag names on the dataset details page
- [x] * Tabs on dataset details page don't look clickable (no cursor change or highlight)
- [x] * Not obvious in location search that you're supposed to type something above that line above the map
- [x] the regions on the map still have a white highlight outline but I can’t click them
- [x] * The link under "Source" isn't clickable
- [ ] ~Error loading stats, homepage is generally slow.
Featured datasets aren't showing.~
<img width="1252" alt="error loading stats" src="https://user-images.githubusercontent.com/2201814/35662446-480fbad6-076c-11e8-9e93-6f7a187e0976.png">

- [x] Style doesn't seem right. @philipgrimmett any input on this?
<img width="960" alt="screen shot 2018-02-01 at 4 25 37 pm" src="https://user-images.githubusercontent.com/2201814/35662513-a03a26ce-076c-11e8-9a46-ad07665a10c2.png">

- [x] Can we get rid of this Chrome auto-select yellow bar thing? I don't see it on other search engines in chrome.
<img width="963" alt="screen shot 2018-02-01 at 4 25 57 pm" src="https://user-images.githubusercontent.com/2201814/35662549-d27a5f1e-076c-11e8-92e1-eeb9b4e0503d.png">

Location is missing:
- [x] Search icon
- [x] Helper text in grey
<img width="530" alt="screen shot 2018-02-01 at 4 28 41 pm" src="https://user-images.githubusercontent.com/2201814/35662578-fc406708-076c-11e8-97c4-22211676f155.png">

See here for designs: https://invis.io/HVF8ORL7P#/272862064_searchResults_01_03_01

- [x] When I have a filter selected, I don't get inverted colours. See [the designs](https://invis.io/HVF8ORL7P#/272885175_searchResults_01_04_01) for what it should look like.
<img width="651" alt="screen shot 2018-02-01 at 4 30 15 pm" src="https://user-images.githubusercontent.com/2201814/35662615-3ba9d4c4-076d-11e8-9c88-6b824e37d6b0.png">

- [x] Padding seems off for the calendar. Cancel and Apply should live under the calendar box. Please verify with: https://invis.io/HVF8ORL7P#/272885175_searchResults_01_04_01
<img width="589" alt="calendar" src="https://user-images.githubusercontent.com/2201814/35662840-74b08f32-076e-11e8-84dc-a2670c7cf569.png">

- [x] There's no way to clear a tab, as shown in here: https://invis.io/HVF8ORL7P#/273108817_searchResults_01_04_06

- [x] I'd rather not show this page in this state and introduce the concept later on. @AlexGilleran you ok with this? (project page)

- [x] When I have some filters applied and do a new search, the filters hang around on the page for a 0.2 hot second, while everything else moves.

- [x] The tabs need an icon instead of 'next': https://invis.io/HVF8ORL7P#/272862066_searchResults_01_01
 ![tab](https://user-images.githubusercontent.com/2201814/35663179-f60fd690-076f-11e8-93fc-1dea0708331e.png)

- [x] ![publishers___data_gov_au](https://user-images.githubusercontent.com/2201814/35663141-c4419734-076f-11e8-99bc-c5330fea52f6.png)

**Comment by tkeuneman** [comment]
<img width="1252" alt="error loading stats" src="https://user-images.githubusercontent.com/2201814/35662446-480fbad6-076c-11e8-9e93-6f7a187e0976.png">

Error loading stats, homepage is generally slow.

**Comment by tkeuneman** [comment]
<img width="960" alt="screen shot 2018-02-01 at 4 25 37 pm" src="https://user-images.githubusercontent.com/2201814/35662513-a03a26ce-076c-11e8-9a46-ad07665a10c2.png">

Style doesn't seem right. @philipgrimmett any input on this?

**Comment by tkeuneman** [comment]
<img width="963" alt="screen shot 2018-02-01 at 4 25 57 pm" src="https://user-images.githubusercontent.com/2201814/35662549-d27a5f1e-076c-11e8-92e1-eeb9b4e0503d.png">

Can we get rid of this Chrome auto-select yellow bar thing? I don't see it on other search engines in chrome.

**Comment by tkeuneman** [comment]
<img width="530" alt="screen shot 2018-02-01 at 4 28 41 pm" src="https://user-images.githubusercontent.com/2201814/35662578-fc406708-076c-11e8-97c4-22211676f155.png">

Location is missing:
- [ ] Search icon
- [ ] Helper text in grey

See here for designs: https://invis.io/HVF8ORL7P#/272862064_searchResults_01_03_01

**Comment by tkeuneman** [comment]
When I have a filter selected, I don't get inverted colours. See [the designs](https://invis.io/HVF8ORL7P#/272885175_searchResults_01_04_01) for what it should look like.
<img width="651" alt="screen shot 2018-02-01 at 4 30 15 pm" src="https://user-images.githubusercontent.com/2201814/35662615-3ba9d4c4-076d-11e8-9c88-6b824e37d6b0.png">

**Comment by t83714** [comment]
Preview `Ballarat Car Parking Areas Web Feature Service API Link` data and got the following error:
```
Problem loading URL
A problem occurred while initialising Terria with URL parameters.
```
![image](https://user-images.githubusercontent.com/674387/35662670-7fce4e28-076d-11e8-89e5-c03ace6be13f.png)

**Comment by tkeuneman** [comment]
<img width="589" alt="calendar" src="https://user-images.githubusercontent.com/2201814/35662840-74b08f32-076e-11e8-84dc-a2670c7cf569.png">

Padding seems off for the calendar. Cancel and Apply should live under the calendar box. Please verify with: https://invis.io/HVF8ORL7P#/272885175_searchResults_01_04_01

**Comment by tkeuneman** [comment]
There's no way to clear a tab, as shown in here: https://invis.io/HVF8ORL7P#/273108817_searchResults_01_04_06

**Comment by tkeuneman** [comment]
![publishers___data_gov_au](https://user-images.githubusercontent.com/2201814/35663141-c4419734-076f-11e8-99bc-c5330fea52f6.png)

**Comment by tkeuneman** [comment]
![tab](https://user-images.githubusercontent.com/2201814/35663179-f60fd690-076f-11e8-93fc-1dea0708331e.png)

The tabs need an icon instead of 'next': https://invis.io/HVF8ORL7P#/272862066_searchResults_01_01

**Comment by tkeuneman** [comment]
When I have some filters applied and do a new search, the filters hang around on the page for a 0.2 hot second, while everything else moves.

**Comment by tkeuneman** [comment]
![publishers___data_gov_au](https://user-images.githubusercontent.com/2201814/35663234-4888f1e0-0770-11e8-9c2f-f7c1eb3074a7.png)

I'd rather not show this page in this state and introduce the concept later on. @AlexGilleran you ok with this?

**Comment by tkeuneman** [comment]
Small

**Comment by AlexGilleran** [comment]
Verified in QA except for https://github.com/TerriaJS/magda/issues/538
