### ISSUE TITLE
Make format sleuther recognise title case, sentence case, camel case and acronyms

### ISSUE THREAD

**Issue by tkeuneman** [TerriaJS/magda#394]
- [ ] For file formats
- [ ] For open licenses

_Right now it has to be an exact match for us to recognise something as open license etc_

**Comment by AlexGilleran** [comment]
Talked to @tristochief - the format sleuther as just merged isn't case sensitive. Acronyms/abbreviations is configurable so we can tune that as we go.

License detection is part of the linked-data-rating sleuther but it's already case/acronym insensitive.
