### ISSUE TITLE
Update documentation to correct problems that held up Jacky

### ISSUE THREAD

**Issue by AlexGilleran** [TerriaJS/magda#400]
Jacky had a bunch of problems onboarding because of incorrect or missing parts of the documentation:

- No instruction to install `gtar` on MacOS machines even though you need it
- No instruction to actually install docker - although you can use the `minikube` docker daemon you still need the command line tools
- The docs instruct you to run `npm run dev` for combined-db even though this doesn't make a lot of sense anymore, it's much easier to just use `combined-db` in minikube and port-forward
- Put the big architecture pic from the blog post into the doco to map out the services.

**Comment by kring** [comment]
> The docs instruct you to run npm run dev for combined-db even though this doesn't make a lot of sense anymore, it's much easier to just use combined-db in minikube and port-forward

Surprisingly, `npm run dev` in `magda-combined-db` does run the DB in minikube and port-forward.  But it does it using the old k8s yml files which are increasingly broken, rather than the new helm hotness.

**Comment by t83714** [comment]
Maybe not closely related to this issue--- sometimes, I feel some issues may caused by newer version library I installed via `npm` by default. Do you think it's a good idea to just commit `package-lock.json` to the repository?

**Comment by AlexGilleran** [comment]
I'm happy with it - @kring have you come around on the package-lock.json issue?

**Comment by kring** [comment]
I don't really know the Lerna implications, but a lockfile makes good sense for Magda in principle.

**Comment by t83714** [comment]
I probably can run some tests around implication of `package-lock.json` once I solved some recent issue of my local dev env.
I am also happy to contribute to this document ---- I think I am the one who will be benefited from it the most :-)

**Comment by tkeuneman** [comment]
Medium
