### ISSUE TITLE
Search release QA round 2

### ISSUE THREAD

**Issue by chloeleichen** [TerriaJS/magda#436]

**Comment by steve9164** [comment]
- [ ] Links don't route properly (http://magda.surge.sh/dataset/ds-dga-5ccd7fbf-4755-4c62-907e-4df847b389ee/details)

**Comment by tkeuneman** [comment]
<img width="794" alt="psma_geocoded_national_address_file__g-naf__data_gov_au" src="https://user-images.githubusercontent.com/2201814/35886591-afbabaf0-0be5-11e8-84dd-43f6675faa49.png">

**Comment by tkeuneman** [comment]
<img width="1151" alt="psma_geocoded_national_address_file__g-naf__data_gov_au_2" src="https://user-images.githubusercontent.com/2201814/35886716-1854a74c-0be6-11e8-8384-68186bbd8fd4.png">

**Comment by tkeuneman** [comment]
<img width="708" alt="cumulative_total_tax_returns_received_data_gov_au" src="https://user-images.githubusercontent.com/2201814/35887159-7caa2edc-0be7-11e8-9f0f-df3ae822cffe.png">

See if you can replicate here: http://magda.surge.sh/dataset/ds-dga-5ccd7fbf-4755-4c62-907e-4df847b389ee/details

**Comment by tkeuneman** [comment]
<img width="989" alt="screen shot 2018-02-07 at 9 21 13 am" src="https://user-images.githubusercontent.com/2201814/35887414-4a87f762-0be8-11e8-9991-acd94bb00bb7.png">

In search results, when I hover over a file format, it underlines the text to indicate I can click on it, but it doesn't go anywhere. Either hide the underline or we can link directly to the file (which sounds like it has more implications)

**Comment by tkeuneman** [comment]
<img width="1114" alt="publishers___data_gov_au" src="https://user-images.githubusercontent.com/2201814/35887501-8f443794-0be8-11e8-958f-4b6b81ca0560.png">

Geophysical description is header size (unless that is really their name, in which case, we need to fix that)

**Comment by tkeuneman** [comment]
<img width="1120" alt="publishers___data_gov_au_2" src="https://user-images.githubusercontent.com/2201814/35887650-1b40cfaa-0be9-11e8-8610-86d7a5403062.png">

Is the publishers list alphabetised? It seems weird that this is the results on page 90
