### ISSUE TITLE
New search bar

### ISSUE THREAD

**Issue by tkeuneman** [TerriaJS/magda#448]
As discussed, floating particles a la https://youtu.be/-MJiR5IksEk?t=1m57s that float randomly (ignoring mouse interactions).
When a user starts to input any text into the field, the particles move closer to the search icon then hover around there.

**Comment by AlexGilleran** [comment]
Is this still valid @tkeuneman ?

**Comment by tkeuneman** [comment]
Closing. Irrelevant. Fickle designer whims.
