### ISSUE TITLE
Header labelling mis-spelling

### ISSUE THREAD

**Issue by tkeuneman** [TerriaJS/magda#474]
Also noticed that Datasets Page - Click Dataset Headings may have a typo, should it have 2 click URLs
Inline images 1
Any Page - Click Footer Links also may have a typo
Inline images 2

**Comment by chloeleichen** [comment]
@tkeuneman I can't see the screenshot you attached, can you have a look plz

**Comment by tkeuneman** [comment]
![screen shot 2018-02-19 at 10 58 38 am](https://user-images.githubusercontent.com/2201814/36358515-dfdf5ede-1563-11e8-85cb-d30262c45c12.png)
Found it!

**Comment by AlexGilleran** [comment]
This is really confusing me... are you working on this @tkeuneman ? Because you've assigned it to yourself...

... also what are those screenshots of? The storybook?

**Comment by tkeuneman** [comment]
This is an SEO thing that somebody brought to my attention but we're unable to replicate or get further clarification on (hence assigning it to myself). Happy to close it.
