### ISSUE TITLE
Create banner and feedback form for S.DGA

### ISSUE THREAD

**Issue by tkeuneman** [TerriaJS/magda#475]
- [x] Banner that says 'Welcome to the new Search.Data.Gov.Au. Go back to the old Data.gov.au'
- [x] Feedback form

**Comment by tkeuneman** [comment]
Designs available at: https://invis.io/D2FWXC4WJ3M

**Comment by tkeuneman** [comment]
For the feedback form: 
- [ ] Name is optional
- [ ] Email is mandatory
- [ ] Feedback is mandatory

**Comment by t83714** [comment]
More details regarding @tkeuneman 's  previous note:
The following changes are required:

1> Added (*) to Email & Feedback fields heading.
2> Added tooltip to display the validation error.
3> The distance between right border of the feedback form and browser window should be same as the bottom border

Required changes have addressed by PR https://github.com/TerriaJS/magda/pull/507
