### ISSUE TITLE
Implement New Dataset Page Design (Desktop)

### ISSUE THREAD

**Issue by t83714** [TerriaJS/magda#500]
This issue is about implementing new dataset page design according to @tkeuneman 's design page here:
https://invis.io/J4FSMUCWZ8S#/279453753_dataset_01_01_final

~The scope of work does **NOT** include:~ 
(Updated 14th Mar 2018: will keep this issue as the main container for tracking all required work for new dataset page rather than close it earlier)

The following items are tracked by separate issues:

1> Map Previewer section #483
2> Chart Previewer section #499 
3> Report an issue with this dataset button #503 
4> Open Data Stories #511 

This issue will also only cover desktop version design.

Mobile device optimization will be covered by a sperate issue (#501 ).

Requirement updated on 28th Feb 2018:
- The quality indicator should use Aspect `dataset-linked-data-rating`->`star` field.
This star is an integer ranged from 0 - 5.
The quality indicator on search result page uses a different `quality` field. but, eventually, it will produce the similar result.

Requirement updated on 1st Mar 2018:
- Confirmed with @tkeuneman yesterday Files and APIs section can display links in the same way no matter whether it's broken or not.

Broken links issue #487 will be addressed later after this issue has been finalized.

Requirement updated on 7th Mar 2018:
- Files & Apis should show different icons according to its types.

All possible types are:
- Archive (e.g. Zip)
- Document
- GIS (e.g. maps)
- Presentations
- Spreadsheets
- Tabular
- Raster graphics (images)
- Tiff (images)
- API
- HTML

Available SVG icons can be found at issue #460 
More info regarding this can be found from: 
https://confluence.csiro.au/display/MAGDA/Dataset+page+icons

**Comment by t83714** [comment]
The latest changes for this issue can be found from branch [dataset-page-style](https://github.com/TerriaJS/magda/tree/dataset-page-style)

**Comment by t83714** [comment]
Issue regarding the page design: https://github.com/TerriaJS/magda/issues/301

**Comment by tkeuneman** [comment]
- double check the font colours and sizes. Seems a bit off
- Should also read 'show full description' not 'show all description'

**Comment by tkeuneman** [comment]
![screen shot 2018-03-12 at 10 41 02 am](https://user-images.githubusercontent.com/2201814/37260005-3997fd94-25e2-11e8-8a6d-6c662ea9e12d.png) 
Hide the blue border on selection.

![screen shot 2018-03-12 at 10 42 09 am](https://user-images.githubusercontent.com/2201814/37260012-469dc848-25e2-11e8-91bb-e059b68b6f88.png)
Double check the spacing on the download icon

![screen shot 2018-03-12 at 10 47 03 am](https://user-images.githubusercontent.com/2201814/37260042-b9cce272-25e2-11e8-98bf-461c13e9cd35.png)
Should be size 16pt (same as paragraph), not 18pts

![screen shot 2018-03-12 at 10 47 39 am](https://user-images.githubusercontent.com/2201814/37260049-ce5a08b4-25e2-11e8-9825-d971221a95f5.png)
Stars are out of alingment

Can we hide the data preview and map preview if none is available?

Can you change the gap for the icons in Files and APIs to 6.333%? It's currently 8.333% and is a bit wide.
![screen shot 2018-03-12 at 10 52 12 am](https://user-images.githubusercontent.com/2201814/37260127-80dc79e0-25e3-11e8-80b9-94fac9c5fabd.png)

**Comment by tkeuneman** [comment]
Looking good!

**Comment by tkeuneman** [comment]
Note: This work does not include the open data use cases.

Am unable to test the chart data viz.
