### ISSUE TITLE
New Dataset Page Mobile Device optimisation 

### ISSUE THREAD

**Issue by t83714** [TerriaJS/magda#501]
This issue is about the further adjustment on the new dataset page so that the mobile view of the page will match @tkeuneman 's design here:

https://invis.io/J4FSMUCWZ8S#/279453752_dataset_mobile_01_01

This issue should be taken care of after issue #483, #499 #503, #511 & #500 have been done.

Updated on 12th Mar 2018:
Based lastest new of dataset page (as of 12th Mar 2018), the following items need to be adjusted for the mobile devices according to current mobile version design:
- [x] Page Header: 
![image](https://user-images.githubusercontent.com/674387/37259440-6cc05cd2-25da-11e8-8158-dd27b29377c0.png)
- [x] Search box: different style
- [x] Publish info line: created & updated date is not available on the mobile version: ![image](https://user-images.githubusercontent.com/674387/37259458-a9aff508-25da-11e8-9a98-4fce4498e06c.png)
- [x] Chart & Datagrid Preview (different config interface design)
- [x] Map Preview (different size)
- [x] Files & APIs section: buttons should be shown in the left bottom corner.

**Comment by tkeuneman** [comment]
QA on mobile against the [design](https://projects.invisionapp.com/share/J4FSMUCWZ8S#/screens/279453752_dataset_mobile_01_01):
- [ ] Capital 'S' in Search for open data
- [ ] Should only show four lines of text before 'full description is prompted
- [ ] 'Show full description' is always highlighted when I go to any dataset page, and I'm not sure why
- [ ] Data quality underline should end after the word, not include the ':' and the stars
- [ ] There should be lines underneath each file type. See mockup for more information

![screenshot_20180327-110333](https://user-images.githubusercontent.com/2201814/37939680-e7d4adca-31af-11e8-90bd-3181ae852615.png)

**Comment by t83714** [comment]
Regarding `Should only show four lines of text before 'full description is prompted`, we will implement the following behavior and see how it looks like:
- Hide content after 500 characters on desktop view
- Hide content after 400 characters on mobile view

**Comment by AlexGilleran** [comment]
- Search bar is off center
- Tags are are weirdly aligned
- Chart wraps off the side of the screen - should probably hide it completely?

**Comment by chloeleichen** [comment]
200 char on mobile is about 4 lines of text
