### ISSUE TITLE
As a user, I want to see the highest quality map per dataset

### ISSUE THREAD

**Issue by tkeuneman** [TerriaJS/magda#504]
Use these file formats for the map preview per dataset:
1. csv-geo-au
2. ArcGIS MapServer
3. WMS
4. CZML
5. KML
6. GeoJSON
7. ArcGIS Feature Server
8. WFS

**Comment by t83714** [comment]
Hi @tkeuneman 

I think (let me know if I were wrong) the requirement of this item has been covered by issue #483 requirement item 1.

The similar feature has been implemented for that issue. The differences are:

1> We put in a different list (based on which format can be supported better) from higher priority to lower priority:

1. GeoJSON
2. WFS
3. WMS
4. csv-geo-au
5. KML

I will keep adding new format (that proven to be supported well ) and adjust the order of this list in future.

2> Besides this list, we will also check the result of broken link sleuther to determine which format to use.

**Comment by tkeuneman** [comment]
Ok, great, thanks @t83714
