### ISSUE TITLE
I get a NaN error if I put the dates on extreme ends

### ISSUE THREAD

**Issue by tkeuneman** [TerriaJS/magda#505]
![Screen Shot 2018-02-26 at 1.25.42 pm.png](https://images.zenhubusercontent.com/5a5b31cc4b5806bc2bc2a818/ce78d8da-c8bd-486f-a7c6-927e8902fec7)

**Comment by AlexGilleran** [comment]
Can you still reproduce this @tkeuneman ?

**Comment by tkeuneman** [comment]
Nope!
