### ISSUE TITLE
The date filter doesn't stick to a date timeline

### ISSUE THREAD

**Issue by tkeuneman** [TerriaJS/magda#506]
- It says '8' in the from column, but I can't filter by that date, as it then shows '1908' in the selected date
- The date selector then shows me 1908 - 1800, which is chronologically wrong.

![Screen Shot 2018-02-26 at 2.37.55 pm.png](https://images.zenhubusercontent.com/5a5b31cc4b5806bc2bc2a818/569a75e7-42a5-451b-a2c2-f60939aadaea)

**Comment by tkeuneman** [comment]
![screen shot 2018-02-26 at 2 37 30 pm](https://user-images.githubusercontent.com/2201814/36652488-1aea78d4-1b03-11e8-88e8-a92fda13c787.png)
![screen shot 2018-02-26 at 2 37 51 pm](https://user-images.githubusercontent.com/2201814/36652490-1f022cfa-1b03-11e8-86ff-80de4ae06b9b.png)
![screen shot 2018-02-26 at 2 37 55 pm](https://user-images.githubusercontent.com/2201814/36652493-21a1c164-1b03-11e8-827d-0a81d9ea9905.png)

**Comment by tkeuneman** [comment]
A couple of things, not really related to this ticket specifically, so we can create another one if needed: 
Current design: 
![screen shot 2018-03-13 at 11 15 21 am](https://user-images.githubusercontent.com/2201814/37315847-d8413410-26af-11e8-9db8-f961039195b2.png)
- [ ] All icons should be white when a filter is applied
- [ ] Follow the line pattern present here: https://invis.io/HVF8ORL7P#/272862061_searchResults_01_02_03

**Comment by chloeleichen** [comment]
@tkeuneman what did you search to produce that issue with date?

**Comment by AlexGilleran** [comment]
@chloeleichen I think the issue is fine, it's just UI tweaks now.

And that's all the evidence I need to think that this is getting confusing, so I've moved it to #667 :).
