### ISSUE TITLE
Add a privacy policy to DGA

### ISSUE THREAD

**Issue by tkeuneman** [TerriaJS/magda#516]
- [ ] Link feedback form to this
- [ ] Create page with content from DTA: https://www.dta.gov.au/privacy-statement/

**Comment by t83714** [comment]
Requirements:
- Create a page served at URL https://search.data.gov.au/page/privacy-policy with content from https://www.dta.gov.au/privacy-statement/ with the following changes to the page content:
  - change `dta.gov.au` to `data.gov.au` under `scope` section
  - remove `MailChimp` section
  - change the email address behind the link `You can request information by email` to `data@digital.gov.au`
- Add `Privacy Policy` link to this page on current feedback form (under `Cancel` & `Send ` button in the right bottom corner)

**Comment by tkeuneman** [comment]
Design tasks:
- 0.75rem for the 'privacy' link in the feedback form
- the feedback form X seems out of alignment now.

I am waiting on DTA to confirm the text is good to go :)

**Comment by t83714** [comment]
More Requirements:
- Add Privacy Page link to page footer, under `Blog` link
- On feedback form, the font size of the `Privacy Policy` should be same as `Cancel` button

**Comment by t83714** [comment]
Made the following changes at commit: defceaf826a2b3f69ff2c12c50271574b07abeed
- Added privacy policy to the page footer
- Adjusted x button alignment on the feedback form
- Changed `Privacy Policy` link size on the feedback form

Will send a demo link to @tkeuneman for feedback again once DTA confirmed the page content
