### ISSUE TITLE
Create Data Quality page

### ISSUE THREAD

**Issue by tkeuneman** [TerriaJS/magda#517]
Designs: https://invis.io/H6G237RDVEW

- [x] Create page
- [x] Create link if someone clicks on the data quality tooltip

**Comment by AlexGilleran** [comment]
@tkeuneman where should the link go in the footer?

**Comment by tkeuneman** [comment]
I'm actually happy to omit this from the footer. Editing the description to reflect this. Thanks for checking in @AlexGilleran

**Comment by tkeuneman** [comment]
@sukhrajghuman Design QA is all good

**Comment by tkeuneman** [comment]
@sukhrajghuman I'm happy to say it's resolved. Et tu?

**Comment by sukhrajghuman** [comment]
@tkeuneman Yup
