### ISSUE TITLE
Homepage: new header

### ISSUE THREAD

**Issue by tkeuneman** [TerriaJS/magda#543]
![Screen Shot 2018-03-12 at 3.29.39 pm.png](https://images.zenhubusercontent.com/5a5b31cc4b5806bc2bc2a818/16cdd6dd-c0a9-4e53-a87b-3a593160dce2)

Designs: https://www.figma.com/file/F9ts1TVYBqkO14z2YPh5dSJq/Homepage_MAGDA_V4_12032018_TK
Log in to Figma for developer mode.

This ticket includes: 
- [x] Updated links in the header. Datasets goes to all datasets (so a search when you enter *)
- [x] Use cases go to blog.data.gov.au
- [x] Sign in is hidden at the moment, but we will add it once we have integration/the service
- [x] Australian government logo in header
- [x] Adding the data.gov.au logo

**Comment by t83714** [comment]
@tkeuneman we probably want to update the screenshot as it looks like an outdated one.

**Comment by tkeuneman** [comment]
@t83714 yes, I mentioned that the source of truth should be the design link, not the screenshot, otherwise I'll be spending most of my days updating screenshots in Github! Hope this helps.

Note: For ease of use, the one design link has all the components and mobile and desktop versions.

**Comment by t83714** [comment]
@tkeuneman 
No problem~ will keep checking the design link~
The only problem is the design link doesn't come with any text description/comments regarding the functionality / requirements. Not sure if invison has a comment function --- it will be good if it does so we can have all information of a task in one place.

**Comment by tkeuneman** [comment]
Comments included. Thanks @t83714

**Comment by tkeuneman** [comment]
Maybe have a look at the mobile designs so that it reflects that.

**Comment by t83714** [comment]
@tkeuneman Is it the header area of mobile designs you referred to?
Mainly: 
- Missing Gov logo 
- DATA.GOV.AU should be centered with `DATA` in red?

**Comment by tkeuneman** [comment]
Yes, it's here: https://www.figma.com/file/F9ts1TVYBqkO14z2YPh5dSJq/Homepage_MAGDA_one-source-of-truth?node-id=327%3A85

- [ ] There's a gradient that goes over the image. See mock up for more info
- [ ] The search icon needs to be shrunk to match the mock up. Check the text size as well
- [ ] The search box has a shadow, a box radius and no stroke
- [ ] Hide 'Explore QLD road data' lozenge
- [ ] Latest news should transition up

**Comment by tkeuneman** [comment]
Links for transition is available here: https://drive.google.com/file/d/1NwlGpcZRYEJUFk2Un58whoCPvweezoen/view?usp=sharing
https://drive.google.com/file/d/1Ir4-ViPzgn_eCuafhT3lViCBu8YzJYfY/view?usp=sharing

Note that the transition is for desktop, but it should also occur when a mobile user clicks on 'latest news'

**Comment by t83714** [comment]
Thanks a lot~ it's much more clear now~
