### ISSUE TITLE
Homepage: Search bar component on homepage, search results, dataset page and mobile

### ISSUE THREAD

**Issue by tkeuneman** [TerriaJS/magda#544]
![Screen Shot 2018-03-12 at 3.41.46 pm.png](https://images.zenhubusercontent.com/5a5b31cc4b5806bc2bc2a818/9c08d3aa-75eb-4731-9d06-649a461b6f15)
![Screen Shot 2018-03-12 at 3.42.46 pm.png](https://images.zenhubusercontent.com/5a5b31cc4b5806bc2bc2a818/69670740-6e5e-4f13-bdcd-8273eb438752)

- [x] Transparency, colour etc
- [x] New search is reflected in the homepage, search results, dataset and mobile pages
- [x] SVG for search icon is here: https://drive.google.com/open?id=18E6VXonTeRMasAgSITbhdjLsg7FUYGgT

**Comment by tkeuneman** [comment]
- [ ] Search bar is missing the line for the start of text
![screen shot 2018-03-22 at 12 17 35 pm](https://user-images.githubusercontent.com/2201814/37745798-0e40e21e-2dcb-11e8-8228-fe9d2dd6f0dd.png)

- [ ] Search font weight should be _light_

- [ ] Search icon should be the same size as the font (it's currently bigger)

- [ ] Search bar underline should have get thicker when a user starts inputting text. See prod design for example

**Comment by chloeleichen** [comment]
re: Search bar is missing the line for the start of the text
Discussed with Tash, since we need to calculate the length of that underline using already rendered text, we are going to leave that one for now
