### ISSUE TITLE
As an end user, I want to remember my search while looking at a dataset page so that I can go back or run it again

### ISSUE THREAD

**Issue by tkeuneman** [TerriaJS/magda#545]
Right now, if I search for 'visas', the search box remembers my input on the search results but wipes the text when I'm on the dataset page. Show the text input in the search field when a user is on a dataset page. 

This does two things: reminds a user of how they got there, and allows them to run the search again without hitting the back button.

**Comment by chloeleichen** [comment]
This is related to saving search in local storage/cookies, just need to take the latest one and show in searchbox @t83714

**Comment by AlexGilleran** [comment]
Create some kind of `?searchQuery=` parameter on dataset links from the search page to populate the search box on the dataset page.

**Comment by chloeleichen** [comment]
Using `q="xxx"` to keep in consistence with current DGA.

**Comment by tkeuneman** [comment]
QA 👍🏼
