### ISSUE TITLE
Background image link and heading under search box

### ISSUE THREAD

**Issue by tkeuneman** [TerriaJS/magda#546]
![Screen Shot 2018-03-12 at 3.47.23 pm.png](https://images.zenhubusercontent.com/5a5b31cc4b5806bc2bc2a818/a822e74b-4205-4e70-8e3a-cb9f6ea797fc)

- [x] Add background image
- [x] Add a tagline to the homepage
- [x] Have a lozenge that shows a link to the dataset, blog post or event that is related to the background image. This means that DTA needs a way to update this going forward (on Github)
~Make webpack or something create different widths for `srcset`~
~Mobile: hide lozenge, position image properly, format as `srcset`~

For now this is just ONE image / tagline defined statically.

**Comment by chloeleichen** [comment]
use amazon config in conjunction with media query and react-responsive to load image responsively, can confirm only smallest image is downloaded for small screen

**Comment by tkeuneman** [comment]
Design work:

- [ ] Font weight for tagline needs to be 200 (seems like it's coupled with some other things in the header, so double check this)

**Comment by tkeuneman** [comment]
- [ ] Check the padding on the 'Explore QLD road data' as it seems squished
