### ISSUE TITLE
Homepage: news/documentation articles

### ISSUE THREAD

**Issue by tkeuneman** [TerriaJS/magda#547]
![Screen Shot 2018-03-12 at 4.04.21 pm.png](https://images.zenhubusercontent.com/5a5b31cc4b5806bc2bc2a818/4c95e920-7217-4cc5-bb9c-b9ffea5480ca)

Designs: https://www.figma.com/file/F9ts1TVYBqkO14z2YPh5dSJq/Homepage_MAGDA_V4_12032018_TK

- [ ] Defined in markdown
- [ ] Ability for a maintainer to prioritise news components (from left to right)
- [ ] Layout is NOT DYNAMIC - article one is the leftmost box, article 2 is the top middle box etc. Text should be written to fit in those boxes.
- [ ] Images are to be uploaded somewhere and linked to
- [ ] Link to article, or dataset, or toolkit, or external source
- [ ] Please note the shadows on each box and the spacing
- [ ] Mobile/responsive versions

**Comment by t83714** [comment]
Should only heading & image inside the story box be clickable

**Comment by tkeuneman** [comment]
You can complete this by using the content here: https://github.com/TerriaJS/magda/issues/772

**Comment by tkeuneman** [comment]
Thanks @t83714 still waiting on copy for this.

**Comment by tkeuneman** [comment]
Updated copy is here: https://github.com/TerriaJS/magda/issues/772#issuecomment-382246519
