### ISSUE TITLE
External links in the footer aren't clickable

### ISSUE THREAD

**Issue by AlexGilleran** [TerriaJS/magda#550]
E.g. the API docs - `href` is fine, HTML looks ok in general but if you click nothing happens. Looks like a rogue click handler maybe?

**Comment by t83714** [comment]
@AlexGilleran 
Done some tests.
It seems it doesn't happen on local test site and only happen to <a> tags (not only within footer but all <a> e.g. homepage news) that have target attributes:
```
<a target="_blank">...</a>
```
Looks like a CSP issue --- maybe we should set `allow-popups` to sandbox?
Created a PR here https://github.com/TerriaJS/magda/pull/566
When you got a chance, we probably can push to dev site to have a test

**Comment by AlexGilleran** [comment]
Fixed by #566
