### ISSUE TITLE
Feedback form error

### ISSUE THREAD

**Issue by chloeleichen** [TerriaJS/magda#553]
hover over `Send` button when form is filled cause error, it does not prevent the form from being sent, but should be addressed anyways. 
<img width="718" alt="screen shot 2018-03-13 at 11 49 18 am" src="https://user-images.githubusercontent.com/7508939/37316713-c681bf38-26b4-11e8-8e2c-dbd7c5cfd103.png">

**Comment by t83714** [comment]
fixed by PR https://github.com/TerriaJS/magda/pull/555
