### ISSUE TITLE
Re-develop pagination design

### ISSUE THREAD

**Issue by chloeleichen** [TerriaJS/magda#557]
**New designs**: https://www.figma.com/file/B635GhKdrAZM4c1V94NBljUq/Smarter-Conversations?node-id=166%3A2

Don't have access? Ping @tkeuneman 

Note: Ignore the search results layout and only focus on the pagination. 

- [ ] Pagination shows 1 - 5 pages as default. When a user starts toggling through, please follow bing's pattern of having a ... (we currently have this ... design so please re-use what we have): https://www.bing.com/
- Pay attention to the way the numbers jump once you're on the 6th or 12th page.

Example of current ...:
<img width="315" alt="screen shot 2018-03-28 at 11 19 40 am" src="https://user-images.githubusercontent.com/2201814/38001711-f90c2c6a-3279-11e8-9ec3-1ce785e38f6d.png">

Due to elasticsearch limitation, search like 
`start=28090&limit=10` 
and `start=10000&limit=10` returns no results, it means results later than 10000 are not accessible

**Comment by AlexGilleran** [comment]
Designs are done for this, they're at https://www.figma.com/file/B635GhKdrAZM4c1V94NBljUq/Smarter-Conversations?node-id=166%3A2

**Comment by tkeuneman** [comment]
Pagination shows 1 - 5 pages as default. When a user starts toggling through, please follow bing's pattern of having a ... (we currently have this ... design so please re-use what we have): https://www.bing.com/
Pay attention to the way the numbers jump once you're on the 6th or 12th page.

**Comment by t83714** [comment]
Summarize `Bing`'s behavior:
- Rule 1: The maximum total no. of  `page no. buttons` is 7 (including a `...` button) unless total page no. is less than 7
- Rule 2: The minimum total no. of  `page no. buttons` is 5 unless total page no. is less than 5
- Rule 3: There should be 2 buttons on the right hand side of the `current page button` unless ( `total page no.` - `current page`) is unless than 2. 
- Rule 4: `Page 1` button should always be the first button
- Rule 5: Buttons on the left hand side of `current page button` should be listed sequentially (higher page no to lower, from right to left) one by one until `page 1` or total button no. reaches the no. specified by rule 1 & 2. If any page no. are left, a `...` button will be created.

**Comment by tkeuneman** [comment]
Thanks so much @t83714
