### ISSUE TITLE
New Homepage Design

### ISSUE THREAD

**Issue by t83714** [TerriaJS/magda#568]
The purpose of this issue is to link all homepage related issues together so we won't miss anything.

A new branch has been created: https://github.com/TerriaJS/magda/tree/new-homepage
And major function has been broken into smaller components on this branch.

Those issues are:
- #546 Including 
    - background images & adjustment (need to change `src/Pages/HomePage.js`)
    - TagLine: `src/Pages/HomePageComponents/TagLine.js`
    - Lozenge: `src/Pages/HomePageComponents/Lozenge.js`
- #547 Stories: Stories Component can be found from: `src/Pages/HomePageComponents/Stories.js`
- #544 SearchBox changes: SearchBox Component has been broken into the different versions for home page & other pages here:  `src/Components/SearchBox/SearchBox.js`
- #543 Header changes: Header Component can be found from: `src/Components/Header/Header.js`

**Comment by philipgrimmett** [comment]
@chloeleichen @t83714 just a heads up that the news card and mobile search field shadows have been updated for consistency across the whole site. Also, at this stage all cards and the mobile search field have a 4px corner radius.
