### ISSUE TITLE
Publishers page is called "Publishers" in header and "Publisher Index" in footer

### ISSUE THREAD

**Issue by AlexGilleran** [TerriaJS/magda#571]
Should only be one.

**Comment by sukhrajghuman** [comment]
![image](https://user-images.githubusercontent.com/20184809/38071759-e4a73a8a-336e-11e8-80be-edb8e4174b5c.png)

I don't think this is an issue anymore? @AlexGilleran

**Comment by AlexGilleran** [comment]
Makes sense to me.
