### ISSUE TITLE
Update footer

### ISSUE THREAD

**Issue by tkeuneman** [TerriaJS/magda#573]
![Footer.png](https://images.zenhubusercontent.com/5a5b31cc4b5806bc2bc2a818/bd94b934-e221-4f32-9c03-d2b2337a1de4)

Reflect these links/words

**Comment by sukhrajghuman** [comment]
@tkeuneman which link should "Architecture" point to?

**Comment by sukhrajghuman** [comment]
I've pointed it to this:

https://raw.githubusercontent.com/TerriaJS/magda/master/doc/magda-basic-architecture.png

**Comment by tkeuneman** [comment]
I think this ties up with the ticket that @adamzerella was working on, where we have a link to MAGDA in the footer. 

@AlexGilleran is there anything you'd like the 'architecture' to point to, like the Medium blog post you did?

**Comment by AlexGilleran** [comment]
I think just "Powered by Magda" with the link to github is better than an architecture link.

**Comment by tkeuneman** [comment]
Still under Data.gov.au or under Developers?

**Comment by AlexGilleran** [comment]
@sukhrajghuman Can we leave "Powered by Magda" in under "Developers" but remove "API Docs" and "Architecture" ?
