### ISSUE TITLE
Make data61 logo link to data61

### ISSUE THREAD

**Issue by AlexGilleran** [TerriaJS/magda#575]

**Comment by AlexGilleran** [comment]
@adamzerella actually it'd be better if this opened in a new window, sorry!

**Comment by adamzerella** [comment]
How dare you! Nah, all good dude -> https://github.com/TerriaJS/magda/pull/682

**Comment by adamzerella** [comment]
This has been merged as of #682, is this in QA?

**Comment by AlexGilleran** [comment]
Eh let's just close 👍
