### ISSUE TITLE
For mobile: when the hamburger is clicked and the menu is activated, the hamburger symbol should turn into an X

### ISSUE THREAD

**Issue by tkeuneman** [TerriaJS/magda#577]
Right now it remains unchanged.

To mimic: https://dribbble.com/shots/2420240-Menu-to-X-Animation

SVG of X:
[Xsvg.zip](https://github.com/TerriaJS/magda/files/1854808/Xsvg.zip)

**Comment by adamzerella** [comment]
Reopened, moving to QA
