### ISSUE TITLE
Omit 'unspecified' from the publishers filter

### ISSUE THREAD

**Issue by tkeuneman** [TerriaJS/magda#580]

**Comment by AlexGilleran** [comment]
@tkeuneman should it also be omitted from Format?

**Comment by AlexGilleran** [comment]
In general this would be a nice introduction to the search api for someone who was keen to work on it :)

**Comment by tkeuneman** [comment]
Lose 'unspecified' from all the filters, but still keep them in the results until a user starts filtering...hope that makes sense.
In other words, if I have no file filters applied, I can still see unspecified file types in the results. If I only filter by 'csvs', the 'unspecified' files are filtered out.
