### ISSUE TITLE
When on a dataset page, I want to be able to click on the organisation and go to the organisation page

### ISSUE THREAD

**Issue by tkeuneman** [TerriaJS/magda#588]
- [ ] Open organisation page on same tab

**Comment by adamzerella** [comment]
@tkeuneman Did you mean the dataset search results here also?

<img width="1042" alt="screen shot 2018-04-16 at 11 43 46 am" src="https://user-images.githubusercontent.com/1501560/38786496-bcefe1bc-416b-11e8-8159-d5046d8067fb.png">

Or just after selecting a dataset?

<img width="869" alt="screen shot 2018-04-16 at 11 46 41 am" src="https://user-images.githubusercontent.com/1501560/38786546-0ada5074-416c-11e8-9bed-18e190753705.png">

**Comment by tkeuneman** [comment]
I meant only after visiting the dataset page, but I'm interested in your opinion on this.

**Comment by adamzerella** [comment]
@tkeuneman I think either option is fine, one idea might be to a add organisation link (seperate tab) on the search results page.

Then a direct link (same tab) when viewing the dataset? Let me know if this doesn't make sense..

**Comment by tkeuneman** [comment]
@adamzerella It's best to link to the specific organisation's page on S.DGA. For example, Australian Institute of Health and Welfare should go to: 
https://search.data.gov.au/publishers/org-dga-8c67ca4b-8119-4ef5-a512-48d53da5104d
