### ISSUE TITLE
When I hover over a file format icon, it should show me helper text

### ISSUE THREAD

**Issue by tkeuneman** [TerriaJS/magda#590]
Dataset page: 

e.g. shp file will have Shape show on hover

<img width="1184" alt="screen shot 2018-04-10 at 4 16 04 pm" src="https://user-images.githubusercontent.com/2201814/38539225-8aa50830-3cda-11e8-86f6-f406b962be70.png">

**Comment by AlexGilleran** [comment]
@tkeuneman do we have the text for every file type written somewhere?

**Comment by tkeuneman** [comment]
Should be covered by the work @t83714 and I did on introducing icons for file types: https://confluence.csiro.au/display/MAGDA/Dataset+page+icons
