### ISSUE TITLE
Add helper text for search icon when a user hovers overs it

### ISSUE THREAD

**Issue by tkeuneman** [TerriaJS/magda#594]
- [ ] Icon says 'Search'

**Comment by sukhrajghuman** [comment]
@tkeuneman 
something like this or...? 

![screen shot 2018-03-22 at 10 17 12 am 2](https://user-images.githubusercontent.com/20184809/37744876-b38814b4-2dc5-11e8-940d-d7230dc88528.jpg)

**Comment by tkeuneman** [comment]
👏🏼
