### ISSUE TITLE
Upgrade node-sass so that watch mode compiles new scss files

### ISSUE THREAD

**Issue by steve9164** [TerriaJS/magda#601]
Upgrading to at least `v4.6.0` should fix this problem. See https://github.com/sass/node-sass/issues/1891

**Comment by maxious** [comment]
We're now at node-sass v4.8.3 is this fixed? https://github.com/TerriaJS/magda/blob/master/magda-web-client/package.json

**Comment by adamzerella** [comment]
Yes, I believe so: https://github.com/TerriaJS/magda/issues/603
