### ISSUE TITLE
Improve Search 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/magda#61]
Adding tasks from workshop on 31 May 17:

- [x] fix issue with "Business names by ASIC as CSV" example search query - @AlexGilleran 

- [x] fix issue with "trees in Victoria" example search query - @AlexGilleran 

- [x] search/query syntax help page needs to be created and linked from search examples box - @cam-grant @chloeleichen 

- [ ] review of filter UI - @cam-grant 

- [x] publishers sidebar in search results: use list of publishers selected in publishers filter, take top 5 and display details for each - @chloeleichen @cam-grant 

- [x] publisher filter - clear command should close popver panel - @chloeleichen 

- [x] Investigate & fix (if broken) date range filter - @AlexGilleran @chloeleichen 

- [x] Investigate and fix (if broken) location filter - @AlexGilleran @chloeleichen

**Comment by AlexGilleran** [comment]
@cam-grant did you do a review?

**Comment by cam-grant** [comment]
@AlexGilleran Yep I'll check it out. It's looking good, but there's bits and pieces we could tighten up.

**Comment by kring** [comment]
Calling this one done.
