### ISSUE TITLE
Mobile search results

### ISSUE THREAD

**Issue by tkeuneman** [TerriaJS/magda#611]
Designs: https://invis.io/R9GF4EWPTCQ

**Comment by tkeuneman** [comment]
![screenshot_20180327-095817](https://user-images.githubusercontent.com/2201814/37937499-abe69828-31a5-11e8-8f75-cde0f22f3728.png)
- [ ] Keyboard should dismiss when I hit the return key
- [ ] Recent search shows for the search I just ran
- [ ] Give feedback should be hidden when they keyboard is present
- [ ] All modal dialogs should fit within the screen size, including padding around the dialog
- [ ] Apply/cancel should be visible at all times (currently, on a large pixel, I have to scroll to see it
(
![screenshot_20180327-100451](https://user-images.githubusercontent.com/2201814/37937838-197efeec-31a7-11e8-99ac-d632fd9c72a2.png)
![screenshot_20180327-100504](https://user-images.githubusercontent.com/2201814/37937839-19a9d3f6-31a7-11e8-8653-122e50c2bfa0.png)
![screenshot_20180327-100657](https://user-images.githubusercontent.com/2201814/37937840-19d355be-31a7-11e8-961c-57016853eb1e.png)

**Comment by chloeleichen** [comment]
Re: Give feedback should be hidden when they keyboard is present

This is an android only problem and there's not much we can about it (without doing something very hacky). Maybe we can look at moving the feedback button to somewhere else for mobile?

**Comment by tkeuneman** [comment]
@chloeleichen This will be redundant once the feedback button is hidden.

**Comment by tkeuneman** [comment]
Mock up for modal dialogs fitting within the screen size: apply/cancel should be visible at all times.

![pixel 2](https://user-images.githubusercontent.com/2201814/38653568-c31763b4-3e4e-11e8-9b2c-9d648aaf54dc.png)
