### ISSUE TITLE
would you mind to provide a online demo or a introduction video?

### ISSUE THREAD

**Issue by xycloud** [TerriaJS/magda#630]

**Comment by AlexGilleran** [comment]
https://search.data.gov.au is the best demo we have at the moment - it's all running on Magda :).

We don't have a video demo at the moment - that's a good idea though, it'd come in useful if we could keep it up to date.

**Comment by AlexGilleran** [comment]
So what we're going to do now is provide feature introductions with each new release combined with gifs of that feature, kind of like [TerriaJS does](https://medium.com/terria/terriajs-v5-3-0-released-96afda5b22c)
