### ISSUE TITLE
We need a logo for Magda

### ISSUE THREAD

**Issue by AlexGilleran** [TerriaJS/magda#632]
It'll go nicely along with the other logos in the footer, and we can put it on Gitter, Github etc.

https://www.youtube.com/watch?v=_94_xYM8X6U

**Comment by ajbar7** [comment]
Toby showed me this and I put this together. The star at the end has the same number of points  in the PDPS.

![magda](https://user-images.githubusercontent.com/7380633/37754648-81ce2d24-2df6-11e8-96c3-c2dc78f4ec79.jpg)

**Comment by ajbar7** [comment]
With a bigger star

![capture](https://user-images.githubusercontent.com/7380633/37754709-cb44d732-2df6-11e8-8e23-9ab63ffbe579.PNG)

**Comment by AlexGilleran** [comment]
🤔 not bad

**Comment by nilfanif** [comment]
hi, what do you think about this modern logotype? ![](https://i.imgur.com/aDCV6jk.png)

**Comment by nilfanif** [comment]
Another modern variation 
![image](https://user-images.githubusercontent.com/16274923/37818992-91704312-2eae-11e8-80d5-5fdd7ebaa286.png)

**Comment by tkeuneman** [comment]
Hi @nilfanif Thanks, these look fab. Did you design them? Where did you get your inspiration from? We're an open-source project so if we were to use one of these, you would have to sign an open-source agreement. Let me know how you feel about that.

**Comment by nilfanif** [comment]
Yeah i designed it, honestly i don't remember where i got the inspiration for that logo, i've been doing logo design for some time. You can check my portofolio here https://dribbble.com/danielyovanda

and of course i agree to sign the open source agreement.

Btw which one do you like? i personally prefer the first one, it is a logotype made of custom font.

**Comment by AlexGilleran** [comment]
Yeah I think the first one is awesome :100:

**Comment by tkeuneman** [comment]
@nilfanif the first one is amazing. Would you be able to create a pull request for it? We'd love to start using it.

**Comment by AlexGilleran** [comment]
Preferably with an SVG or something vector :)

**Comment by nilfanif** [comment]
Alright i'll prepare the files and create a pull request

**Comment by nilfanif** [comment]
Hi, i created a pull request, can you check it? #1137

**Comment by AlexGilleran** [comment]
🎉
