### ISSUE TITLE
magda-web-client only has devDependencies and no dependencies

### ISSUE THREAD

**Issue by AlexGilleran** [TerriaJS/magda#654]
... this can't be right?

Needs to be cleaned up.

**Comment by kring** [comment]
That's correct, the web client has no runtime dependency on any node_modules.
The server has some of course.

**Comment by AlexGilleran** [comment]
So if I run `npm install` in `magda-web-server` does it know to pull `react` into `magda-web-client` so that it can run?

**Comment by kring** [comment]
React isn't needed to run the client. It's only needed to build the client. That's a `devDependency`.

**Comment by kring** [comment]
Terria maps work the same way. The only regular dependency of NationalMap is `terriajs-server`:
https://github.com/TerriaJS/nationalmap/blob/master/package.json#L15
