### ISSUE TITLE
UI Tweaks to the Date Filters

### ISSUE THREAD

**Issue by AlexGilleran** [TerriaJS/magda#667]
(Spun out from #506)

A couple of tweaks to the date filters
Current design:
![image](https://user-images.githubusercontent.com/900555/37887984-8e7fbd5e-3110-11e8-98dd-c836d07c865e.png)

All icons should be white when a filter is applied
Follow the line pattern present here: https://invis.io/HVF8ORL7P#/272862061_searchResults_01_02_03

**Comment by tkeuneman** [comment]
It's reproducible if you add a couple of filters without refreshing the page.
