### ISSUE TITLE
Change New Homepage StoryBox layout to Flexbox

### ISSUE THREAD

**Issue by t83714** [TerriaJS/magda#673]
The new Homepage StoryBox design requires column width ratio hard to achieve via 12 grid columns system. Implement it using Flexbox will be more flexible (works better while user changes screen width)

**Comment by AlexGilleran** [comment]
Spacing is inconsistent: 
![image](https://user-images.githubusercontent.com/900555/38064300-031176fa-3349-11e8-9b47-a47a76729c17.png)

**Comment by chloeleichen** [comment]
Fixed in https://github.com/TerriaJS/magda/pull/677
