### ISSUE TITLE
Add example search queries + "learn more" link to homepage

### ISSUE THREAD

**Issue by cam-grant** [TerriaJS/magda#69]
Please add the following sample queries + a "Learn about the new search" link to the homepage (see attached drawing). "Learn more link should point to the search syntax static page (http://magda-dev.terria.io/page/search-syntax).

Example queries:

- Business Names by ASIC as CSV
- Taxation Statistics from 2013
- Trees in Victoria

![01 01 home](https://user-images.githubusercontent.com/10275015/27521754-b9e3785c-5a63-11e7-9eb3-23b5161a9b9d.png)

**Comment by chloeleichen** [comment]
Done
