### ISSUE TITLE
Hide the * when I click on the Dataset link in header

### ISSUE THREAD

**Issue by tkeuneman** [TerriaJS/magda#707]
<img width="648" alt="screen shot 2018-03-29 at 11 26 44 am" src="https://user-images.githubusercontent.com/2201814/38063297-15cfcc38-3344-11e8-8c48-1508e5eee436.png">

**Comment by chloeleichen** [comment]
Just want to point out: when there is actually no search string (http://localhost:6108/search?q=) there is no search result, but the search box looks the same as if you are searching for all dataset(*).
