### ISSUE TITLE
Get rid of the shadow for multiple selected things in a list

### ISSUE THREAD

**Issue by tkeuneman** [TerriaJS/magda#722]
![Screen Shot 2018-03-29 at 11.54.07 am.png](https://images.zenhubusercontent.com/5a5b31cc4b5806bc2bc2a818/ca45b031-6a15-41ec-b071-ddd21043147f)

**Comment by sukhrajghuman** [comment]
hey @tkeuneman  which shadow are you referring to?

**Comment by tkeuneman** [comment]
These ones! 
![68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3561356233316363346235383036626332626332613831382f63613435623033312d366131352d343165632d623037312d646464323130343331343766__922x496_](https://user-images.githubusercontent.com/2201814/38474328-d3d8aa84-3be0-11e8-88d2-f77f493c4835.png)

**Comment by tkeuneman** [comment]
@sukhrajghuman if you are working on this, just assign it to yourself and put it in progress :)
