### ISSUE TITLE
Grid System Change / Cleanup

### ISSUE THREAD

**Issue by AlexGilleran** [TerriaJS/magda#765]
We currently use the mui grid system.

If we're going to change to ~GOLD~design systems/gov.au UI that presumably means changing to their grid system.

~_However_ the we have a bunch of classnames in our html that no longer reference any actual styles, but would match up with the new styles, which means we've got to go through all of them and make sure they still look OK.~
The classnames won't clash because the govau classes only work within an au-grid element, but we should still go through and clean them up if they shouldn't be in there.

We don't want two grid systems at the same time on a permanent basis, so we should have some plan for swapping out mui grid for govau grid.

Or should we just stick with mui?

**Comment by chloeleichen** [comment]
We decided we will progressively swap in the GOLD. the grid system will be a good place to start with.
