### ISSUE TITLE
Update 'About' page content

### ISSUE THREAD

**Issue by tkeuneman** [TerriaJS/magda#773]
Copy change for the About page:

**Data.gov.au** is a product of the Government’s Declaration of Open Government. It is a place anybody can access data published by the Australian Government and public institutions.

Most of the data available is free of charge and can be visualised using the in-built mapping tools.
Individuals and organisations are encouraged to use the data on this site for research, study or applications that add value to the global community.

In addition to open datasets, data.gov.au now includes information about unpublished data and data available for purchase.

Geospatial datasets on data.gov.au and from other spatial indexes are now available through the National Map.

H2: How do I share?
If you’re an Australian Government entity or private business that provides services to the community, you can register and create an account to share your data sets.
Before you begin, do a quick search of existing organisations to see if your own agency is already listed. If they are, the listed contact can help you to log in and publish your data sets. If not, you can register for the first time.

H2:Registering for the first time?

We need some basic information to create an account. This includes a username, contact name, and email address.

1. Enter this information to create your account.
2. You will be redirected to your profile page. To set up your profile, select 'Manage'.
3. It is important you fill out your profile completely, including your agency’s logo as your account image. We recommend you use a group inbox for your organisations contact email. This way users can contact the right area or team if they have questions, rather than contacting a specific person. This future-proofs your account for when data stewards are on leave or move organisations. If you choose to include a contact phone number, we recommend a shared or switchboard number for the same reasons.

H2: Publishing for the first time? 

Many agencies are excited but nervous the first time their share data. You should always consider privacy and cleanliness of data before sharing. Information regarding privacy can be found in our [Privacy Policy ](https://toolkit.data.gov.au/index.php?title=Publishing_your_data#Privacy_and_security) and in our [Open Data Toolkit](https://toolkit.data.gov.au/index.php?title=Publishing_your_data). Our Open Data Toolkit also includes useful information and links to other open data sources, on topics like how to form a [policy](https://toolkit.data.gov.au/index.php?title=Policy) about sharing data through to creating a basic data set.

H2: Want to keep in touch?
Subscribe to the new datasets feed or customise a feed below:
Groups - http://data.gov.au/feeds/group/
Tags - http://data.gov.au/feeds/tag/
Search - http://data.gov.au/feeds/custom.atom?q=

**More Information**
Visit the [Open Data Toolkit](https://toolkit.data.gov.au/index.php?title=Main_Page) for more information about how to use data.gov.au and related policies and initiatives.

**Comment by MelanieHotchkiss** [comment]
1. This paragraph should be numbered as a list "Registering for the first time?"
2. 3 links are missing in paragraph under heading "publishing for the first time?"
3. Line breaks are missing in paragraph under heading "want to keep in touch?"
4. Link missing in paragraph under heading "More information"
