### ISSUE TITLE
Update 'Data quality' page content

### ISSUE THREAD

**Issue by tkeuneman** [TerriaJS/magda#774]
This reduces it by a reading level and just replaces some of the big fancy words with simpler ones to match the tone.

h1: Dataset Quality
h2 or h3: How we measure data quality
We calculate data quality based on open data best practices, including Tim Berners-Lee's open data scale. This scale is specific enough to be useful but vague enough to be future-proof. It's adopted by many open data portals around the world.

For each of the following points, we add 20% to the data quality rating. These work like building blocks. For a data set to earn 4 stars, it has to meet the first four steps.

1. Is the data available on the web in any format with an open license?
2. Is it available as structured, machine-readable data? For example, an excel file instead of an image scan of the same table.
3. Is it available in a non-proprietary format? Such as CSV instead of Excel.
4. Does the data have URIs to mark things. so that people can reference your stuff?
5. Do you link your data to other data, or provide information on how the data was collected to provide context?

We will continue to update the data quality rating as research continues. If you have any feedback get in touch, or if you're passionate about data quality, get involved in the Australian Government Linked Data Working Group (link pre-exisiting).

**Comment by t83714** [comment]
`Does the data have URIs to mark things. so that people can reference your stuff?` this line should be
`Does the data have URIs to mark things so that people can reference your stuff?` (remove the stop sign)
