### ISSUE TITLE
Date Filter Disappears for Certain Query Strings

### ISSUE THREAD

**Issue by sukhrajghuman** [TerriaJS/magda#802]
### Problem description

Date filter disappears when applying publisher/format filters. This only happens for certain search strings.
For example I've noticed it does it for "vic" and not "nsw".

see FacetTemporal.js : 145

### Problem reproduction steps

See below gif

### Screenshot / Design / File reference
![datefilterdisappears](https://user-images.githubusercontent.com/20184809/38798826-113d41d0-41a6-11e8-8236-71b0b7064e51.gif)

**Comment by t83714** [comment]
I think it's expected behavior and introduced by PR: 
https://github.com/TerriaJS/magda/pull/498
For solving issue #505

**Comment by sukhrajghuman** [comment]
Ohh my bad
