### ISSUE TITLE
Confusing page numbering

### ISSUE THREAD

**Issue by kring** [TerriaJS/magda#81]
Page 1 of the search results displays this:
![image](https://user-images.githubusercontent.com/924374/27522019-13218114-5a66-11e7-8f78-f1bb59046084.png)

A person seeing this might reasonably assume it's telling them they're on page 2, when really it's telling them that the _next_ page is page 2.  Can we make this clearer?

**Comment by chloeleichen** [comment]
@cam-grant can you have a look

**Comment by cam-grant** [comment]
Yep go with "Page x of y" to indicate the _current_ page, at least for now. I'm not entirely sure though - ultimately the best approach would be to test it with users.
