### ISSUE TITLE
Switching over to gold stage 1 and 2

### ISSUE THREAD

**Issue by chloeleichen** [TerriaJS/magda#826]
### Problem description
We need to switch to gold. Let's do it in baby steps. 

Stage 1:

- [x] Typography
https://github.com/TerriaJS/magda/pull/829
- [x] Color
- [ ] Footer
- [x] Most buttons
- [x] Form elements
- [ ] Tabs, in `DataPreviewVis.js`
- [ ] Call to action
- [x] Grid
- [ ] Header and headings etc
- [x] Link list for tags (https://designsystem.gov.au/components/link-list/ or https://designsystem.gov.au/components/tags/)
- [x] Text input. (https://designsystem.gov.au/components/text-inputs/)

Stage 2:

- [ ]  Checkboxes for filter facet (using their instead: https://designsystem.gov.au/components/control-input/ or https://designsystem.gov.au/components/select/)
- [ ]  Notifications/errors (this thing: https://designsystem.gov.au/components/callout/ and https://designsystem.gov.au/components/page-alerts/)
- [ ] Remove any final mui- classes from JSX (ie. unstyled list and grid)

**Comment by AlexGilleran** [comment]
Closing in favour of an epic #932 so we can part it out and assign it :).
