### ISSUE TITLE
Distribution page looks just like the dataset page

### ISSUE THREAD

**Issue by kring** [TerriaJS/magda#85]
It even says "Home / Dataset" in the breadcrumbs.  The distinction should be made more clear.

**Comment by chloeleichen** [comment]
Added breadcrumb

**Comment by kring** [comment]
I think something like the CKAN breadcrumb would work well:
![image](https://user-images.githubusercontent.com/924374/27715574-8efc3988-5d7b-11e7-95b8-31b0beb7c8ce.png)

I'd probably drop that "Organizations" link the breadcrumb, though (leave the organization name).  and possibly add a "back to search results" link when you get there via searching, rather than relying exclusively on the browser back button.

**Comment by kring** [comment]
This isn't critical for this release though.

**Comment by AlexGilleran** [comment]
This'll be handled while designing the new dataset pages.
