### ISSUE TITLE
Record download has wrong MIME type

### ISSUE THREAD

**Issue by adamzerella** [TerriaJS/magda#850]
### Problem description
When downloading a record from dataset results page the console logs incorrect MIME type.

### Problem reproduction steps
"https://data.gov.au/dataset/5c99cfed-254d-40a6-af1c-47412b7de6fe/resource/6e2de166-2223-4acd-b034-ace4c974c973/download/taxstats2015summary01historicalratesofpersonalincometax.xlsx" is of type `xlsx` but MIME type is set to `application/vnd.openxmlformats-officedocument.spreadsheetml.sheet`

### Screenshot / Design / File reference
<img width="1046" alt="screen shot 2018-04-24 at 4 32 26 pm" src="https://user-images.githubusercontent.com/1501560/39169970-1bafed06-47dd-11e8-9da0-404ca63c1be8.png">

**Comment by AlexGilleran** [comment]
Not sure we can do much about that given that it's on data.gov.au not search.data.gov.au :(
