### ISSUE TITLE
As a user, don't show me an empty or * result in my recent searches

### ISSUE THREAD

**Issue by steve9164** [TerriaJS/magda#853]
### Problem description
- It's still possible to have an empty search show up in Recent Searches

### Problem reproduction steps
- Not sure exactly how this came about, but it happened on mobile Android (Pixel One, Chrome)

### Screenshot / Design / File reference
![screenshot_20180424-164847](https://user-images.githubusercontent.com/2201814/39170711-dff32442-47df-11e8-9a97-78df0390e440.png)

**Comment by t83714** [comment]
- Empty strings will not be saved since the last PR --- It shows on that screen because it had been saved before last PR merged. It won't happen to new users. Just delete the entry and it won't come back again.
- We do need to change the program logic to exclude `*`
