### ISSUE TITLE
Adjust format sleuther to deal with csiro-oa-app

### ISSUE THREAD

**Issue by steve9164** [TerriaJS/magda#854]
### Problem description
Filtering by format on SDGA currently displays ~2000 results for a csiro-oa-app type. We should make this into a proper datatype.

![image.png](https://images.zenhubusercontent.com/57577ca9bf93871ccd9c433a/226e8fdc-8565-40dd-b8a4-777a72ea9066)

### Problem reproduction steps
Go to search page, search for `*`, look at filters.

**Comment by t83714** [comment]
Will make format sleuther return:
- `CSIRO Open App` for `www:download-1.0-http—csiro-oa-app`
- `html` for `WWW:DOWNLOAD-1.0-http--downloaddata`
