### ISSUE TITLE
As a user that is looking for a particular dataset, I want to know that I can request it if I can't find it

### ISSUE THREAD

**Issue by tkeuneman** [TerriaJS/magda#874]
### Problem description
- As a user, I want to see the option to suggest a new dataset once my search is irrelevant (to be researched and tested)
- Form field expands, can be filled, can receive an error and can get a success message.
- A user can dismiss this box and they don't see the prompt until the next search is received 

### Screenshot / Design / File reference
Shown: https://www.figma.com/file/B635GhKdrAZM4c1V94NBljUq/Smarter-Conversations?node-id=346%3A1018
Expanded:
https://www.figma.com/file/B635GhKdrAZM4c1V94NBljUq/Smarter-Conversations?node-id=346%3A4050
Sent:
https://www.figma.com/file/B635GhKdrAZM4c1V94NBljUq/Smarter-Conversations?node-id=347%3A0

Please take error message from the others

**Comment by AlexGilleran** [comment]
Tracking in #867
