### ISSUE TITLE
Hide the 'Sign in' button as it doesn't work at the moment

### ISSUE THREAD

**Issue by tkeuneman** [TerriaJS/magda#879]
### Problem description

Hide the 'Sign in' button as it doesn't work at the moment
- Doesn't work for Facebook
- Doesn't work with existing DGA credentials
- Google sign in is untested

### Problem reproduction steps

Go to S.DGA and sign in is in the header.

**Comment by AlexGilleran** [comment]
@tkeuneman changing the link back to linking directly to `data.gov.au` has resolved this right?

**Comment by tkeuneman** [comment]
Yup. Closing this one out.
