### ISSUE TITLE
Make GNAF and Admin Boundaries featured datasets

### ISSUE THREAD

**Issue by kring** [TerriaJS/magda#90]

**Comment by chloeleichen** [comment]
I found gnaf: http://magda-dev.terria.io/dataset/19432f89-dc3a-4ef3-b943-5326ef1dbecc/details 
but which is the Admin Boundaries dataset?

**Comment by kring** [comment]
This one I think: http://magda-dev.terria.io/dataset/bdcf5b09-89bc-47ec-9281-6b8e9ee147aa/details
@ajbar7 can you confirm?

**Comment by ajbar7** [comment]
That's the one!

**Comment by kring** [comment]
@chloeleichen did this.
