### ISSUE TITLE
data.json sources

### ISSUE THREAD

**Issue by ajbar7** [TerriaJS/magda#91]
List of data.json sources already available from data.gov.au

|data.json end point|harvest_source_title|
|---------------------|------------------|
|http://data.logancity.opendata.arcgis.com/data.json|Logan City ArcGIS JSON Harvest|
|http://opendata.launceston.tas.gov.au/data.json|City of Launceston ArcGIS JSON Harvester|
|http://data-1.hobartcc.opendata.arcgis.com/data.json|City of Hobart ArcGIS JSON Harvest|
|https://data.melbourne.vic.gov.au/data.json|Melbourne JSON Harvester|
|http://www.data.act.gov.au/data.json|ACT JSON Harvester|
|http://data.moretonbay.qld.gov.au/data.json|Moreton Bay ArcGIS JSON Harvest|
|http://data.esta000.opendata.arcgis.com/data.json |ESTA Emergency Marker ArcGIS JSON Harvester|

**Comment by kring** [comment]
These have all been added. Some may currently be broken when you click on the link to the details page, due to #95.
