### ISSUE TITLE
Review the importance of distribution page and showing license

### ISSUE THREAD

**Issue by tkeuneman** [TerriaJS/magda#924]
### Problem description

Usability testing showed that most people didn't find the license information super important. We can either make it less visually obvious or show it below an expand. 

This ticket also involves reviewing the content of the distribution page and seeing if we can merge it with the dataset page.

**Comment by MelanieHotchkiss** [comment]
@maxious has opinions on this - pls chat to him

**Comment by AlexGilleran** [comment]
Duplicate
