### ISSUE TITLE
Do we need a seperate 'resource' page if we're going to send people to source?

### ISSUE THREAD

**Issue by ajbar7** [TerriaJS/magda#93]

**Comment by chloeleichen** [comment]
@cam-grant

**Comment by kring** [comment]
IMO, yes!  It's worthwhile to have a consistent page for details of a distribution before sending the user off to a portal-specific location.  Plus there's no guarantee that distributions coming from, e.g. a CSW server, even have a landing page on their source portal.  And even if we move the map preview to the dataset page, it will be useful to show previews of individual distributions (e.g. a table showing the content of a CSV, a map with the data from this distribution in GeoJSON format even if we've chosen to show the WMS distribution on the main page, etc.)

**Comment by ajbar7** [comment]
@kring - if previews are available what's stopping them all being on the dataset page? Something a sleuther could explore the dataset and an appropriate preview if a compatible resource exists.

**Comment by kring** [comment]
Only that it will be super crowded in some cases.  Imagine putting the preview for all of the distributions in this dataset on one page: http://data.gov.au/dataset/taxation-statistics-2013-14
I think we should only put the "best" preview (as determined by a sleuther) on the dataset page, and then the distribution page should have the preview for just that distribution, if we're able to provide one.

**Comment by ajbar7** [comment]
@kring that sounds good
