### ISSUE TITLE
Switch to Design Systems: Tabs

### ISSUE THREAD

**Issue by AlexGilleran** [TerriaJS/magda#934]
### Problem description
 in DataPreviewVis.js

**Comment by adamzerella** [comment]
@AlexGilleran The design system doesn't support `Tabs`. The closest thing we can do is use the `Navigation` component that will look a bit like this: 
![screen shot 2018-05-15 at 9 59 36 am](https://user-images.githubusercontent.com/1501560/40029263-d79ee1bc-5826-11e8-9f2e-75278ac3326a.png)

But... it isn't released just yet:
![screen shot 2018-05-15 at 10 01 54 am](https://user-images.githubusercontent.com/1501560/40029316-337449aa-5827-11e8-9a82-05d9c55433ef.png)

I have the unreleased code for the component though, go ahead anyway?

**Comment by chloeleichen** [comment]
This is fixed in the latest master, closing
