### ISSUE TITLE
Projects next page button doesn't work

### ISSUE THREAD

**Issue by kring** [TerriaJS/magda#96]
The UI indicates it's on page 2, but all the items are the same as page 1.

Page 1:
![image](https://user-images.githubusercontent.com/924374/27686744-67eb167a-5d17-11e7-8d9f-315c7ed39b36.png)

Page 2:
![image](https://user-images.githubusercontent.com/924374/27686761-7bbf0792-5d17-11e7-9179-273b07fddee4.png)

**Comment by chloeleichen** [comment]
done
