### ISSUE TITLE
Show "source" in search results

### ISSUE THREAD

**Issue by kring** [TerriaJS/magda#97]
We had this in the previous search.data.gov.au:
![image](https://user-images.githubusercontent.com/924374/27687909-ff3bf0b8-5d1b-11e7-9ca9-0a001324c9cc.png)

At least until we do a better job of curating organization names, showing the source can make the relevance of results a lot clearer.  For example, this search result would be a lot better if it said "Source: Queensland Government" underneath it:
![image](https://user-images.githubusercontent.com/924374/27687973-3ef94728-5d1c-11e7-970b-d27b66b29817.png)

**Comment by chloeleichen** [comment]
done

**Comment by kring** [comment]
Looks like you've just put the label "Source" in front of the organization / publisher.  We want to continue showing the publisher, but also add the source _portal_.  Just like we do on the embedded details page:
![image](https://user-images.githubusercontent.com/924374/27722875-7d0e5d28-5dad-11e7-9165-2aee7059be19.png)

So we should show "Agriculture and Fisheries" just like we were before, and then also add "Source: Queensland Government".

**Comment by kring** [comment]
@chloeleichen did this.
