### ISSUE TITLE
Flip order of start/end in temporal coverage section

### ISSUE THREAD

**Issue by kring** [TerriaJS/magda#98]
Start should be first.

**Comment by chloeleichen** [comment]
Flipping that means the latest date will be on the bottom. I think it makes sense to have the latest on top, seems more natural to me. Google's search has latest on top too: 
<img width="163" alt="screen shot 2017-06-30 at 10 44 12 am" src="https://user-images.githubusercontent.com/7508939/27716373-3fa312d4-5d81-11e7-840e-553ca28eeb38.png">

**Comment by kring** [comment]
I mean in this thing, not in the search filter.
![image](https://user-images.githubusercontent.com/924374/27716910-ef09b73e-5d84-11e7-9906-ce44cfb3f89a.png)

**Comment by chloeleichen** [comment]
done
