### ISSUE TITLE
Create acronyms based on publisher name

### ISSUE THREAD

**Issue by tkeuneman** [TerriaJS/magda#981]
Create an acronym for the search engine based on the first letter for every word in the publisher name. 

For example, Agriculture and Fisheries will be AF.

**Comment by AlexGilleran** [comment]
> Next iteration would be doing things like ABS = Australian Bureau of Statistics
Jacky actually already did this!

**Comment by AlexGilleran** [comment]
Merged https://github.com/TerriaJS/magda/pull/1088/ but will leave this open until there's unit tests :)

**Comment by t83714** [comment]
Seems case sensitive for the query.
Needs to confirm this and find a way to make it case-insensitive
