### ISSUE TITLE
Homepage articles: Double check spacing

### ISSUE THREAD

**Issue by tkeuneman** [TerriaJS/magda#996]
### Problem description
It looks like there might be double spacing for the homepage articles. What does it look like if we get rid of one of the spaces between paragraphs? Rope me in on this one if you need it. :) 

### Problem reproduction steps
Go to the homepage

### Screenshot / Design / File reference
<img width="1173" alt="screen shot 2018-05-18 at 1 45 24 pm" src="https://user-images.githubusercontent.com/2201814/40215138-0fa0c2c4-5aa2-11e8-966b-c933f40c32d9.png">

**Comment by AlexGilleran** [comment]
@tkeuneman @t83714 manually double-spaced the paragraphs so the ones on the side would end up being the same length as the two in the middle... it looked very weird without it :(.

If we could get some longer blurbs that'd be great :D

**Comment by tkeuneman** [comment]
I'll add it to the convo I'm having with Stephen, the content writer.
