### ISSUE TITLE
Search filters: alignment

### ISSUE THREAD

**Issue by tkeuneman** [TerriaJS/magda#997]
### Problem description
The alignment of the icons should be aligned with the middle of the text labels, not the bottom.

### Problem reproduction steps
Search results page

### Screenshot / Design / File reference
<img width="622" alt="screen shot 2018-05-18 at 1 56 17 pm" src="https://user-images.githubusercontent.com/2201814/40215420-b9ae8124-5aa3-11e8-8566-8c70d614ff13.png">

**Comment by chloeleichen** [comment]
Fixed in https://github.com/TerriaJS/magda/pull/1040
