### ISSUE TITLE
Search filter drop down

### ISSUE THREAD

**Issue by tkeuneman** [TerriaJS/magda#998]
### Problem description
We need to talk about this. 
- Spacing for the list
- Spacing when an item is selected
- Apply should be a primary button
- Clear should be a secondary button

### Problem reproduction steps
Search results page. Click on a filter

### Screenshot / Design / File reference
<img width="479" alt="screen shot 2018-05-18 at 2 01 17 pm" src="https://user-images.githubusercontent.com/2201814/40215486-199e2f08-5aa4-11e8-9876-6698b52e80da.png">
<img width="488" alt="screen shot 2018-05-18 at 2 01 08 pm" src="https://user-images.githubusercontent.com/2201814/40215487-1a579560-5aa4-11e8-8432-d57f4bc77bb6.png">

**Comment by tkeuneman** [comment]
I'll follow up with Chloe on Monday

**Comment by chloeleichen** [comment]
Fixed in https://github.com/TerriaJS/magda/pull/1040
